In [80]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Load and understanding the data

In [81]:
data = pd.read_csv("fifa21 raw data v2.csv").replace('\n','', regex=True)
data

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,Wuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,Oldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,Derry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,Dalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,Dalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

# Classify the data and view the unique value

## Numerical data

In [83]:
numerik = ['int8','int16', 'int32', 'int64', 'float16', 'float32', 'float64']
display(data.select_dtypes(include=numerik).columns)
print(data.select_dtypes(include=numerik).shape)
data_num = data.select_dtypes(include=numerik)
data_num.head(5)

Index(['ID', 'Age', '↓OVA', 'POT', 'BOV', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY'],
      dtype='object')

(18979, 54)

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
0,158023,33,93,93,93,429,85,95,70,91,...,14,8,2231,466,85,92,91,95,38,65
1,20801,35,92,92,92,437,84,95,90,82,...,14,11,2221,464,89,93,81,89,35,77
2,200389,27,91,93,91,95,13,11,15,43,...,90,90,1413,489,87,92,78,90,52,90
3,192985,29,91,91,91,407,94,82,55,94,...,10,13,2304,485,76,86,93,88,64,78
4,190871,28,91,91,91,408,85,87,62,87,...,15,11,2175,451,91,85,86,94,36,59

**Find the uniqe value from numerical data**

In [84]:
for i in data_num:
  print(i)
  print(data_num[i].unique())
  print('\n')

ID
[158023  20801 200389 ... 252757 243790 252520]


Age
[33 35 27 29 28 31 21 34 32 25 26 30 20 24 22 23 19 38 42 36 37 18 17 39
 40 41 16 43 53]


↓OVA
[93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71 70
 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47]


POT
[93 92 91 90 95 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71
 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47]


BOV
[93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71 70
 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48]


Attacking
[429 437  95 407 408 423 392 114 118 316 410 349  86 119 426 374 411 360
 328 383 405 123 420 224 388 397 425 373 365 371 311 396 345 399 400  78
 280 330 403 379 380  94 394 419 339 293 344 390  84 359 372 377 346 389
 386 308 277 382 368 402 292 298 366 352 363 322 361  91 364 341 385 355
 305 321 262  93 375 387 356 253 285 391 353 367  90 295 378 256 338 331
  69 105  85 358 343 319 271 113 350 406 340 393 247 334 351 342 302 329
 354  98 301 115 384 208  72 376  92 258 362  74 417  99 263  88 279 101
 395 100  81  87  55 310  82 117 409 318 323 248 315 381 348 327 309 130
 283 336 369 106 252 320 290 370 126 251 108 335 297 284  80  75 357 270
  97 306 337  73 286 325 326 324 333 103 259 273 313 296  61 312 347 401
 304 278  83  43 314 291 264 272 317 231 250 268  54 261 255  70 281 265
 299 287  68 294  77 219 300 269 332 289 288 107 282 122 244  89 112 274
 276 307 229  96 109  76 125 102 239 227 241 257 254 228 233 124 215 246
 110 245 214 242 266 104  66 303 260  63 230 275  50 238 249 111  67 240
 221 237  56 235 234 243 267 232 203 223  64 213 222 226 225 211 207  52
 173  57 217 236  71 204 216 199  59 189  60 194 116 205 201 193  65 192
 209 218 128 210  79  45 206 162 220  49 197 202 212  58 190 181  51  62
 200 198 195 191 131 185  42 180 182 196 188 169 187 178  53 183 184 186
 165 172  47 171 176 159  46 179 175 167 174 161 170 177 164 134 168 163
 166 158 150 143  48 152 160 148 151 157 154 141 146 147 149 156 153 138
 145 142 139 155 144 136 137]


Crossing
[85 84 13 94 71 79 17 78 18 53 76 58 14 15 75 66 70 68 91 82 20 12 30 77
 88 83 93 90 87 81 73 11 54 62 86 80 55 42 57 65 63 64 52 40 69 47 60  9
 16 44 72 50 56 46 89 34 45 74 49 67 24 35 36 61 19 27 25 10 51 38 43 59
 39 48 23  8 28 92 41 29 32 22 26 37 33 31 21  7  6]


Finishing
[95 11 82 87 94 91 13 14 52 90 64 88 65 85 66 84 10 22 76 81 56 79 57 45
 77 63 86 80 15 33 67 12 72 92 93 51 46 60 75 55 73 83 50 42 39 40  9 68
 48 37 70 78 69  8 53 89 25 62 71 74 44 26 19 32 18 61 58 30 54 36 29 16
 38 59 27 34 47 20 31 49 43 41 28  5  7  6 21 17 35 23 24  4  3]


Heading Accuracy
[70 90 15 55 62 85 59 19 73 11 87 84 80 13 25 91 92 78 46 54 72 64 14 10
 61 58 83 38 69 51 67 86 75 68 16 81 21 79 53 65 82 12 42 48 88 66 76 74
 52 23 40 49 60 44 20 37 71 17 45 77 50 63 43 39 57 56 47 24 18 31 28 35
 34 41 36 93  7 30 89  8 26 33 27 32 22 29  9  5  6]


Short Passing
[91 82 43 94 87 84 45 83 61 79 85 33 55 86 57 81 42 74 93 88 30 65 89 77
 32 50 80 78 90 69 40 92 75 73 34 76 35 70 37 23 44 38 48 26 60 25 46 28
 24 36 51 17 18 39 71 67 27 72 66 20 31 68 29 11 64 62 41 63 19 54 16 22
 49 59 56 14 58 15 21 52 53 12 47 13  8  7]


Volleys
[88 86 13 82 87 89 79 20 83 14 45 75 63 12 11 69 67 56 18 85 62 70 32 40
 47 81 44 84 78 76 90 49 42 64 57 60  8 72 71 59 74 80 73 37 31 38 61 10
 77 68 58 66 30 33 65 27 51 15 16 50 43 35 24 17 34 28  9 39 52 46 22 19
 53 55 48 54 23  5 41 25 21 36 26 29  6  7  4  3]


Skill
[470 414 109 441 448 407 406 138 394 144 363 391 369 110 160 404 381 397
 387 336 400 436 157 395 100 262 427 432 429 380 426 411 358 351 433 365
 403  98 276 386 383  99 413 115 341 375 143 359 309 435 330 325 355  96
 420 412 388 319 269 399 106 402 425 297 312 418 372 352 439 409 349 116
 371 428 104 345 430 295 405 440 422 252 401 417 396 233 377 251 382 368
  84 356 342 410 271 350  83 126 103 370 362 343 328 344 415 378 275 416
 119 127 373 384  77 393 348 317 408 376 300 220  89 107 334  72 390 419
 305 289 398 281 354 102 339 385 139 292  97 421  91 105  73 335 101 340
 337 306 113 122 123 302 364 250 347 333 323 389 361 322  86 367 258 392
  92  90 310 331 338 121 260  82 245 324 346 379 299 284 320 283 108 278
 286 296 315 274  88 114 264 288  94 326 366 117 360 424  93 318 124 125
 327 249  75 332 303 374 239 272 357 353 266 321 277 268 314 294 240  95
 227 112 118 263 280 140 282  81 329 201  87 221 257 285 316 287 307 270
 256 313 311 228 247 254 130  80  85 232 293 298 301 213 168 291 216 290
 308 261 171 267 242 219 248 237 243 279 246 273  78 255 253 230  74 210
 235 231 208 259 304 241 199 224 206  61 129 222 223 141 149 131 225  71
 189 265 226  70 179 192 134 209 173 234  76 236 212  69 218 120 177 238
 204 229 215 165 211 195  64 202 194 190 193 203  67 214  79 205 244 196
 111 187  65 200  63 198 217 135  68 184 167 148 207 142 185 133 191 181
 197  43  66 175 182  51 180 169 186 137 188 176 132  60 178 147 163 183
 162 152 170 172 174 159 161 154 153 128  62 166  53 155  56 151 164 158
  46 150  59  55  58 156 146  52 136  54  47  48 145  40  57]


Dribbling
[96 88 12 95 85 90 27 92 21 70 91 69 13 30 87 65 79 83 23 80 18 93 77 63
 76 16 59 81 11 84 10 75 78 55 15 86 66 67 28 57 64 82 62 19 53 72 50 26
 43 89 73 20 14 68 71 74 22 54 56 61  9 24 60 25  8 17 47 58 46 42 51 52
 49 44 35 48 39 29 40 45 34 31 33 38 41 32  7 37 36  5  6]


Curve
[93 81 13 85 88 79 83 19 18 60 76 63 14 74 77 49 15 80 12 28 86 84 82 61
 71 11 66 16 89 70 21 46 78 67 58 65 48 34 90 59 55 87 62  9 56 36 30 32
 73 69 68 75 45 10 72 64 41 23 47 20 51 25 44 17 54 57 53 33 40 50 39 35
 52 42 37 43 26 31 92 91 29 94 27 38 22 24  8  6  7  5  4]


FK Accuracy
[94 76 14 83 89 85 69 18 63 12 70 64 74 20 11 73 49 61 88 68 28 79 84 48
 67 38 87 53 65 15 31 78 82 10 51 59 19 47 52 57 43 13 77 54 75 86 55 30
 62 32 58 93  8 66 71 81 92 44 17 60 40 16 72 46 35 45 29 21 56 80 24 22
 39 42 26 41  9 37 27 50 33 25 36 91 34 23  7  6 90  5]


Long Passing
[91 77 40 93 81 70 75 44 63 86 71 84 35 59 73 83 64 69 79 82 68 89 76 80
 87 37 65 36 50 53 78 47 74 48 31 85 24 55 90 54 62 32 49 66 67 51 28 46
 52 72 56 41 45 22 88 61 33 12 60 17 27 29 23 38 16 58 34 25 39 21 30 42
 43 57 20 26 18 19 13 15 11 14  9 10  5  8]


Ball Control
[96 92 30 95 88 89 90 77 79 23 46 83 80 85 94 40 84 16 74 91 87 82 78 19
 61 22 34 38 81 25 86 76 69 28 93 75 35 60 63 73 18 71 15 21 72 14 65 20
 24 27 70 33 17 62 64  9 68 67 32 26 66 52 11 57 58 29 12 37 10 36 13 31
 55 59 39 54 56 48 44 51 50 47 49 53  5 42  8 45 43 41  7]


Movement
[451 431 307 398 453 407 460 268 458 254 354 343 284 286 388 378 424 464
 420 399 437 322 367 272 328 448 332 425 435 391 434 400 331 349 429 416
 312 326 418 419 417 386 321 409 374 304 403 351 401 365 414 292 323 299
 433 350 348 413 320 281 427 353 364 410 428 316 381 442 375 288 395 385
 251 319 444 383 298 411 412 415 393 397 443 423 387 422 327 390 362 352
 406 277 361 421 396 384 450 338 363 359 287 297 430 382 377 380 438 449
 257 371 339 341 404 345 394 295 246 265 258 366 294 314 266 405 218 337
 267 220 376 309 283 426 347 244 240 291 340 250 305 290 317 334 355 333
 389 330 318 441 402 344 335 219 264 408 274 373 379 256 229 392 372 360
 262 346 278 248 368 279 269 336 342 236 370 243 315 249 227 329 239 369
 223 282 358 271 313 270 356 263 184 311 436 432 221 301 190 259 308 235
 260 217 275 285 210 234 276 310 447 180 446 300 303 209 247 252 231 357
 226 238 280 440 237 245 296 325 273 306 196 242 199 178 222 445 324 293
 302 289 214 192 206 225 197 241 230 188 202 208 203 216 213 224 439 212
 232 253 228 189 204 205 207 198 168 255 215 194 191 185 145 261 156 201
 193 181 233 195 183 152 211 160 173 170 176 147 143 159 187 169 200 165
 163 177 179 167 139 162 175 155 166 172 174 154 164 182 150 186 146 138
 157 137 135 171 158 161 149 124 144 151 148 141 134 153 126 142 125 132
 127 140 133 130 131 136 122]


Acceleration
[91 87 43 77 94 56 96 38 72 95 60 42 54 79 89 64 66 51 73 57 80 86 85 78
 40 82 76 65 68 90 48 46 88 70 83 84 93 52 74 92 55 58 59 67 81 62 44 71
 69 50 53 45 49 75 41 61 63 35 47 34 36 37 39 30 97 31 33 32 27 28 26 29
 25 17 19 24 15 23 21 20 22 16 18 13 14]


Sprint Speed
[80 91 60 76 89 78 92 47 96 50 79 93 69 52 72 70 90 66 82 63 55 77 86 81
 83 85 65 68 53 43 94 62 58 61 87 64 67 54 88 75 95 73 49 84 56 44 74 51
 57 46 59 71 37 34 33 42 30 35 48 39 45 40 18 38 41 27 32 29 28 36 26 31
 22 25 23 15 20 17 16 24 19 21 12 14]


Agility
[91 87 67 78 96 77 40 92 37 61 93 51 79 84 94 82 60 69 47 52 63 74 59 66
 86 85 57 55 76 75 73 62 72 90 68 64 80 56 48 83 41 81 54 88 33 65 49 71
 89 45 70 43 50 32 42 39 58 36 34 53 46 95 44 38 21 29 35 31 19 26 30 22
 28 24 25 23 27 14 18 15 20]


Reactions
[94 95 88 91 93 92 86 89 87 84 90 83 85 82 81 79 80 74 75 78 77 73 76 71
 70 68 72 66 69 65 67 64 59 60 62 63 61 58 57 56 50 54 53 55 52 32 49 48
 45 51 46 47 37 34 44 40 38 43 41 35 42 33 39 31 36 30 24 29 28]


Balance
[95 71 49 76 83 82 91 37 43 53 86 66 45 35 69 94 92 84 90 48 73 36 41 93
 74 60 79 65 78 61 57 50 68 51 54 77 81 39 75 58 87 85 63 38 88 67 72 62
 80 44 46 42 55 40 70 32 89 52 59 47 64 27 56 30 31 25 34 29 24 96 33 28
 20 23 22 26 21 17 97 19 12 18]


Power
[389 444 268 408 357 420 393 240 404 402 406 437 249 284 400 403 358 381
 382 273 424 264 316 361 355 328 370 350 365 348 411 395 385 257 337 250
 379 371 409 223 398 388 241 347 308 426 378 343 341 262 325 345 359 399
 421 396 315 253 368 336 340 366 387 369 375 260 326 346 373 412 364 279
 376 372 415 356 333 338 342 410 407 430 394 354 331 239 234 392 270 422
 374 360 391 300 335 242 327 215 397 321 390 339 383 265 288 224 351 252
 429 416 380 413 377 405 349 232 386 362 192 320 251 329 271 237 427 259
 255 266 227 353 258 243 263 291 302 306 332 363 256 247 301 287 322 419
 312 245 297 401 344 235 289 233 317 334 216 367 352 318 226 324 219 319
 292 244 423 323 304 208 314 313 193 299 303 311 229 211 225 309 330 238
 305 220 296 212 231 283 207 198 281 384 307 272 298 248 310 267 214 282
 274 280 230 228 221 277 276 285 290 269 246 294 293 195 236 295 217 189
 275 201 278 194 206 218 176 205 185 196 222 204 188 197 209 286 168 254
 200 183 179 159 180 187 164 178 190 213 202 186 191 261 210 203 173 199
 169 152 181 175 184 182 170 160 162 167 177 139 161 172 165 171 128 174
 158 153 166 155 163 151 122 142 143 156 149 144 157 147 154 150 134 140]


Shot Power
[86 94 59 91 80 89 64 66 81 84 88 56 68 79 78 71 82 70 55 76 61 83 51 52
 90 87 62 72 77 74 50 57 58 85 60 75 67 65 93 46 54 69 41 73 40 53 95 43
 63 42 48 31 44 37 49 39 45 38 47 30 33 25 34 36 28 27 32 26 35 23 22 29
 20 24 21 18]


Jumping
[68 95 78 63 62 84 69 52 77 79 90 86 87 93 57 75 66 82 56 32 51 76 72 81
 74 71 67 65 73 64 70 80 85 37 89 60 49 50 83 58 53 59 88 38 92 34 61 46
 43 36 91 39 45 42 40 54 33 55 31 44 35 47 48 30 41 94 28 29 27 24 19 26
 17 15 22]


Stamina
[72 84 41 89 81 76 85 32 86 35 75 88 90 38 43 78 79 96 95 70 82 77 93 94
 87 39 54 80 45 83 69 65 73 91 34 66 71 92 62 67 64 63 68 36 61 74 42 40
 23 44 31 57 20 37 29 30 56 60 52 48 58 25 51 26 27 59 28 53 33 49 97 55
 50 46 24 21 22 15 47 17 19 16 18 14 12]


Strength
[69 78 74 50 86 75 76 92 70 91 80 85 65 72 67 60 84 71 94 63 73 62 54 81
 64 87 58 43 77 66 53 89 68 46 44 61 79 88 59 83 55 34 82 95 56 37 90 57
 93 49 39 51 52 40 48 41 47 35 42 33 45 32 38 30 31 36 29 27 24 28 16 97
 96 20 25 26 23]


Long Shots
[94 93 12 91 84 85 14 79 10 64 78 81 17 16 65 87 18 86 19 15 82 63 74 76
 47 89 70 90 77 13 49 54 88 80 53 58 51 73 66 75 83 30 46 35 71 61 72 69
 43 48 62 41 60 11 26 57 59 68 67  7 27 56 20 52 92 50 22 40 39 44 31 42
  9  6 55 28 23 38 24 25 34 36 29  4  8 45 33 37 21 32  5]


Mentality
[347 353 140 408 356 391 376 341 171 358 396 122 188 363 414 332 386 379
 348 172 382 123 294 378 313 371 331 412 345 377 161 306 387 339 135 360
 138 369 359 170 361 321 397 394 385 366 162 337 362 344 319 315 144 336
 340 373 398 324 300 338 384 139 364 372 134 354 342 308 322 383 263 149
 304 367 357 390 291 279 310 388 375 349 351 365 133 334 303 380 153 392
 169 318 350 352 401 302 325 346 132 399 281 335 403 307 368 141 126 328
 245 131 320 127 421 400 137 374 305  92 316 311 120 389 145 355 148 343
 142 130 121 157 329 323 115 150 298 154 317 295 100 301 326 327 197 273
 287 370 290 103 393 312 297  89 271 299 124 333 258 309 158 272 118 314
 330 292 404 101 280 277 296 248 285 278 109  93 146 286 284 288 105 152
 111 160 119 156  95  99 238 104 266 276 275 265 106 254 293 282 168 260
 136 102 267 113 289  96 270 176 164 128 268 283 244 182 243 240 116 264
 112 274 261 114 269 110 257 179 155 252 262 151 247 108 256 117 249 253
 231 159 163  84 251  97  91  75 147 129 230 242 250 259 125 381  77 175
  82  88  90 165  83 195  87 246 255  85  94 226 216 236 220 107 241 228
 198 239 225 181 233 219 166 183  98 237 235  86 229 217 143 232 209 234
 224 206 227 222  80  78 186 221 173 214 187  79  68 167  81 218 212 199
 210  74 223 208 213 201  72 215 202 205 203 204 190  76 211 207 192  70
 194 196 189  66 193 200  67 191 184  71  64  65  69 177  63  73  51  58
 180 185 174  60  55 178  62  50  59]


Aggression
[44 63 34 76 51 81 27 62 43 83 75 91 23 29 90 65 59 89 48 38 25 87 54 60
 73 74 69 85 70 86 32 40 31 77 84 80 78 79 71 56 42 30 61 58 28 82 46 52
 36 92 55 35 67 37 72 57 50 64 39 47 20 68 15 66 33 93 88 22 24 45 17 18
 26 21 11 41 53 19 12 49 94 16 95 13 14 96 10  9]


Interceptions
[40 29 19 66 36 49 55 11 38 22 90 35 87 15 30 39 88 24 91 82 42 27 41 79
 74 58 20 85 48 83 64 21 50 81 78 28 86 26 34 52 37 80 25 56 23 47 45 77
 84 44 53 18 46 72 61 89 54 63 65 73 16 32 76 59 13 70 31 69 33 17 75 68
 60 51 71 12 57 10 43 67 14  9 62  8  7  6  4  5  3]


Positioning
[93 95 11 88 87 94 91 13 47 92 72 12 90 73 80 85 20 35 76 89 83 77 54 70
 86 16 28 14 84 78 10 75 52 71 81 64 56 15 82 79 44 30 59  7 68 38 48 67
 24 26 34 69 74 32 66 62 65 51 18 31  9 25 49 55 63 27 61 17 39 58 29 50
 40 19  8 42 60 57 37 45 43 53  5  4 36  6 46 41 23 22 33 21  3  2]


Vision
[95 82 65 94 90 79 84 66 80 70 85 44 87 71 83 41 52 86 68 50 77 48 88 30
 61 74 59 73 72 64 91 78 63 57 89 62 56 69 42 67 27 76 81 55 75 60 49 45
 58 22 53 46 25 43 51 40 93 33 31 34 35 39 47 21 32 28 37 36 38 54 24 23
 14 11 15 26 19 18 12 20 17 10 29 13 16  9]


Penalties
[75 84 11 92 88 83 23 70 25 62 71 66 27 47 69 54 44 86 17 90 33 87 73 60
 55 68 91 72 50 78 18 82 40 29 45 43 64 24 59 46 56 81 67 49 61 74 58 63
 79 38 80 32 20 76 77 41 19 26 85 21 52 34 53 65 57 16 42 89 15 13 14 22
 51 37  9 48 12 31 36 39 10 30 35 28  8  7  6]


Composure
[96 95 68 91 93 88 90 65 84 70 66 80 85 69 82 89 81 87 83 86 67 92 94 57
 78 79 75 45 61 76 58 62 77 74 59 55 48 40 64 73 39 71 72 63 60 52 53 56
 44 54 41 32 49 46 31 51 50 25 18 38 30 24 21 36 33 26 23 47 22 28 34 35
 37 43 27 12 42 17 29 13 19 14 16 20 15]


Defending
[ 91  84  57 186  94  96 122  50 100  48 272 259  54  38  89 263  83 147
 264 245 120  52 130 267 205 162 105 241 148 248 266 194 258 117 166  56
 249  92  45 214 140  99 150  59 251 262 243 195 160  40 114 236 244 231
  80 123 253 132 103 257 261  98  78 209 229 230  60 101 206 242 138  61
 256 171 260 226 224  44 131 113 240  77 232 225 109 228 247  93 121 238
 111 128 188 173 250 255  41 144 239 217 106 165 246 235 126 118 203 234
 135 215 175 192 108  39  33 151 156 174  47 216 237 102 227 161 233  67
 213  75 212  36 254 196  88  81 134  53 155 223  43 125  46  51 137  71
  95  35 208 110 170  87 107  55 204 177  69 152 163  37 181 252 159 133
 124 207  82  97  65  42  79 104 211 129  49 157 153 185 189 146  86 112
  73 127  31 220 164 191 219 139  64 183  66 197  90 218  34  72 221 222
 142  63 136 179  85 169 180  74 210  62 187 145 198 184 199  32  30  58
 172 178 116 176  70 202 141 115 193 149  29 201 167 168 182 119 190 200
  76 143 158 154  68  28  27  25  24  26  23  20  21]


Marking
[32 28 27 68 35 38 15 34 25 93 42 84 20 17 47 85 30 89 82 29 56 91 72 59
 79 49 83 86 50 60 94 41 57 78 63 88 90  9 58 74 39 92 45 36 44 87 70 76
 53 80 67 77 12 48 55 75 81 11 64 69 14 24 52 65 19 31 13 10 66 71 54 46
 22 40 18 51 37 43 61 26 73 21  7 33 62 16 23  8  6  5  4  3]


Standing Tackle
[35 32 12 65 30 42 43 19 34 13 93 88 18 10 24 29 53 90 84 48 15 36 89 27
 73 54 41 83 59 67 87 64 14 55 75 45 33 57 21 82 50 86 80 79 31 46 85 40
 44 56 20 70 76 81 71 16 68 37 38 78 39 77 11 74 28 49 47 72 61 51 22 17
 52 63 23 60 25 26  9 62 58 66 69  7  8  6  5]


Sliding Tackle
[24 18 53 29 19 41 16 32 10 86 38 87 11 90 47 85 79 40  8 13 22 60 49 81
 88 55 33 42 14 80 36 12 52 71 46 83 65 84 34 82 77 78 74 20 43 35 69 70
 30 68 45 57 44 21 75 26 51 76 39 48 28 63 59 66 72 17 67 64 31 25 15 54
 58 62 56 23 37 73 50 27  9 61  7  6  4]


Goalkeeping
[ 54  58 437  56  59  51  62 439  42  67 420 440  41  46  63  60  26 435
 424  43  45  52  50  47  53  44 418  15  48 416 153 413  65  64  20 423
  49  55  66  40  57 421  13  39  61 419  21 409  37 406 410  36 408  34
  29 405 403 402 407  16  69 391 401 398 400  22  68 396  38  78  73 399
 390 393 395 397  80  70 389 394 388  27  30  75  71 386  74 378 385 384
 380 392 381  10 387 383 375 382  19 379  24 369 356 368 373 370 372  72
 374 376 364  25 367  17 377 371 365 352 362 359 363 366  82  35 361 358
  76 294  83 357 360 355 354  77 229 350 353 347 351  32 349 169 346 348
 343 345 339 342  33 341  28 119 337 338 340 344 335  98 324 248 334 298
 336 328 331 321 332  81  79 333 278 329 261 325  31 327 330 322 305 326
 283 320 323 318  18 319 316 317 272 315  88 311 310 314 313 307 312 309
 308 301 304 292 303 306 296 289 300 302 297 290 299 293 295 291 288  93
 284 287 286 285 273 282 279 281 280 277 275 276 274 270 271 268 269 267
 260 265 262 266 263 264 251 259 254 257 252 255 256 258 247 250 243 253
 249 245 236 246 234 241 231]


GK Diving
[ 6  7 87 15  9 14 86 13 88 10 84 11  8  5 12 90  3 27 89 80 16 85  2 82
 79 83  4 81 77 18 78 17 75 74 76 73 71 72 52 68 70 54 69 32 66 65 67 61
 22 64 23 40 63 55 19 50 62 58 60 59 56 57 53 51 49 46 48 47 45]


GK Handling
[11 92 13  9  6 14 88  5 85 10 89 87  8 15 12  4 82 81  3  7 25 86 83  2
 80 16 77 79 78 76 84 75 72 74 71 69 73 70 67 68 65 61 62 64 41 63 66 33
 22 17 57 18 54 55 59 49 19 40 60 58 43 45 53 47 56 51 52 50 48 46]


GK Kicking
[15 78  5 12  9 85  7 88 13 16 74 91  6 10  4 93 11 73 14 75  2 31 68 76
  8 80 82  3 87 72 83 77 79 81 69 71 20 67 70 64 65 63 44 60 84 54 48 61
 18 66 17 59 62 90 43 38 58 57 28 40 53 23 47 46 19 51 55 52 56 22 30 25
 42 35 21 49 50 36 45]


GK Positioning
[14 90 10 15  8 11 91 88  7 12 85 86  5 89 13  6 82  4  9 87 33 84 16 83
  2  3 79 81 80 76 78 19 77 17 75 74 73 71 18 72 70 69 66 68 40 64 20 32
 67 62 65 63 24 23 50 55 58 51 59 56 61 57 60 46 54 53 52 47 49 48 43 45
 42 38 44 41]


GK Reflexes
[ 8 11 90 13 10 14 89  6 12 88  7  9 15  5  3 37 85 86  4 16 82 83 84 87
 78 80 20 18 79 81 19 77 17  2 74 71 76 73 75 72 69 46 66 51 70 34 67 23
 68 45 65 21 59 54 47 61 64 63 62 60 58 56 57 55 53 50 52 49 48 44]


Total Stats
[2231 2221 1413 ...  757  747  956]


Base Stats
[466 464 489 485 451 457 470 490 484 455 469 463 468 497 442 439 473 452
 498 449 477 401 446 447 465 430 461 422 476 460 453 467 471 399 424 441
 459 438 437 454 428 445 431 474 421 435 448 475 403 444 443 419 405 420
 423 396 388 482 478 385 394 480 433 450 462 456 436 434 429 400 440 425
 410 458 398 413 373 406 408 472 426 407 432 427 415 481 417 372 380 418
 383 414 409 412 411 386 362 402 390 404 391 416 375 389 361 397 366 392
 393 382 368 387 352 376 384 378 379 341 354 369 395 357 381 377 344 360
 370 338 333 367 363 349 355 345 358 348 374 351 343 342 353 321 350 365
 364 371 327 331 359 347 356 339 319 317 335 346 329 315 324 322 325 332
 336 337 330 316 313 306 307 328 310 340 308 318 334 301 289 302 320 323
 326 311 297 314 304 292 305 312 294 287 300 299 285 303 288 278 296 277
 309 291 283 286 293 295 298 276 282 272 284 290 271 275 279 281 262 263
 280 268 270 269 264 273 265 252 267 257 274 266 259 247 261 251 233 239

## Categorical data

In [85]:
display(data.select_dtypes(include=['object']).columns)
print(data.select_dtypes(include=object).shape)
data_cat = data.select_dtypes(include=['object'])
data_cat.head(5)

Index(['Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Club',
       'Contract', 'Positions', 'Height', 'Weight', 'Preferred Foot',
       'Best Position', 'Joined', 'Loan Date End', 'Value', 'Wage',
       'Release Clause', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'Hits'],
      dtype='object')

(18979, 23)

,Name,LongName,photoUrl,playerUrl,Nationality,Club,Contract,Positions,Height,Weight,...,Loan Date End,Value,Wage,Release Clause,W/F,SM,A/W,D/W,IR,Hits
0,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,NaN,€103.5M,€560K,€138.4M,4 ★,4★,Medium,Low,5 ★,771
1,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,Juventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,NaN,€63M,€220K,€75.9M,4 ★,5★,High,Low,5 ★,562
2,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,Atlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,NaN,€120M,€125K,€159.4M,3 ★,1★,Medium,Medium,3 ★,150
3,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,Manchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,NaN,€129M,€370K,€161M,5 ★,4★,High,High,4 ★,207
4,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,NaN,€132M,€270K,€166.5M,5 ★,5★,High,Medium,5 ★,595

**Find the uniqe value from categorical data**

In [86]:
for i in data_cat:
  print(i)
  print(data_cat[i].unique())
  print('\n')

Name
['L. Messi' 'Cristiano Ronaldo' 'J. Oblak' ... 'R. McKinley'
 "Wang Zhen'ao" 'Zhou Xiao']


LongName
['Lionel Messi' 'C. Ronaldo dos Santos Aveiro' 'Jan Oblak' ...
 'Ronan McKinley' "Zhen'ao Wang" 'Xiao Zhou']


photoUrl
['https://cdn.sofifa.com/players/158/023/21_60.png'
 'https://cdn.sofifa.com/players/020/801/21_60.png'
 'https://cdn.sofifa.com/players/200/389/21_60.png' ...
 'https://cdn.sofifa.com/players/252/757/21_60.png'
 'https://cdn.sofifa.com/players/243/790/21_60.png'
 'https://cdn.sofifa.com/players/252/520/21_60.png']


playerUrl
['http://sofifa.com/player/158023/lionel-messi/210006/'
 'http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/'
 'http://sofifa.com/player/200389/jan-oblak/210006/' ...
 'http://sofifa.com/player/252757/ronan-mckinley/210006/'
 'http://sofifa.com/player/243790/zhenao-wang/210006/'
 'http://sofifa.com/player/252520/xiao-zhou/210006/']


Nationality
['Argentina' 'Portugal' 'Slovenia' 'Belgium' 'Brazil' 'Poland' 'Egypt'
 'France' 'Germany' 'Netherlands' 'Senegal' 'Spain' 'England' 'Scotland'
 'Korea Republic' 'Costa Rica' 'Italy' 'Gabon' 'Croatia' 'Uruguay'
 'Switzerland' 'Serbia' 'Slovakia' 'Morocco' 'Algeria' 'Denmark' 'Hungary'
 'Bosnia Herzegovina' 'Nigeria' 'Cameroon' 'Norway' 'Ghana' 'Mexico'
 'Austria' 'Albania' 'Colombia' 'Chile' 'Ivory Coast' 'Greece' 'Finland'
 'Wales' 'Sweden' 'Togo' 'Czech Republic' 'Russia' 'Venezuela' 'Canada'
 'United States' 'Guinea' 'Montenegro' 'Israel' 'Republic of Ireland'
 'Ukraine' 'Turkey' 'Ecuador' 'Jamaica' 'DR Congo' 'Australia' 'China PR'
 'Armenia' 'Northern Ireland' 'North Macedonia' 'Kosovo' 'Mali' 'Peru'
 'Central African Republic' 'Iceland' 'Burkina Faso' 'Paraguay' 'Japan'
 'Romania' 'New Zealand' 'Iran' 'Angola' 'Tunisia' 'Syria'
 'Dominican Republic' 'Cape Verde' 'Equatorial Guinea' 'Kenya' 'Georgia'
 'Panama' 'Zambia' 'Tanzania' 'Zimbabwe' 'Congo' 'South Africa' 'Moldova'
 'Mozambique' 'Iraq' 'Guinea Bissau' 'Honduras' 'Cuba' 'Cyprus'
 'Lithuania' 'Estonia' 'Madagascar' 'Benin' 'Curacao' 'Saudi Arabia'
 'Gambia' 'Uzbekistan' 'Chad' 'United Arab Emirates'
 'Saint Kitts and Nevis' 'Libya' 'Sierra Leone' 'Philippines' 'Liberia'
 'Bulgaria' 'Comoros' 'Namibia' 'Luxembourg' 'Trinidad & Tobago' 'Bermuda'
 'Thailand' 'Burundi' 'New Caledonia' 'Puerto Rico' 'Bolivia' 'Kazakhstan'
 'Antigua & Barbuda' 'Latvia' 'Malawi' 'Montserrat' 'São Tomé & Príncipe'
 'El Salvador' 'Mauritania' 'Jordan' 'Eritrea' 'Aruba' 'Uganda'
 'Chinese Taipei' 'Azerbaijan' 'Afghanistan' 'Faroe Islands' 'Haiti'
 'Sudan' 'Grenada' 'Lebanon' 'Guam' 'Palestine' 'Belarus' 'Guyana'
 'Rwanda' 'Liechtenstein' 'Saint Lucia' 'Papua New Guinea' 'India'
 'Ethiopia' 'Belize' 'Andorra' 'Guatemala' 'Malta' 'Niger' 'Korea DPR'
 'Barbados' 'Macau' 'South Sudan' 'Singapore' 'Hong Kong' 'Nicaragua'
 'Malaysia' 'Indonesia']


Club
['FC Barcelona' 'Juventus' 'Atlético Madrid' 'Manchester City'
 'Paris Saint-Germain' 'FC Bayern München' 'Liverpool' 'Real Madrid'
 'Chelsea' 'Tottenham Hotspur' 'Inter' 'Napoli' 'Borussia Dortmund'
 'Manchester United' 'Arsenal' 'Lazio' 'Leicester City'
 'Borussia Mönchengladbach' 'Real Sociedad' 'Atalanta'
 'Olympique Lyonnais' 'Milan' 'Villarreal CF' 'RB Leipzig' 'Cagliari'
 'Ajax' 'SL Benfica' 'AS Monaco' 'Wolverhampton Wanderers' 'Everton'
 'Fiorentina' 'FC Porto' 'RC Celta' 'Torino' 'Sevilla FC' 'Grêmio'
 'Real Betis' 'Roma' 'Newcastle United' 'Eintracht Frankfurt'
 'Valencia CF' 'Medipol Başakşehir FK' 'Inter Miami' 'Bayer 04 Leverkusen'
 'Levante UD' 'Crystal Palace' 'Athletic Club de Bilbao'
 'Shanghai SIPG FC' 'VfL Wolfsburg' 'Guangzhou Evergrande Taobao FC'
 'Al Shabab' 'Olympique de Marseille' 'Los Angeles FC'
 'Beijing Sinobo Guoan FC' 'Getafe CF' 'SV Werder Bremen'
 'TSG 1899 Hoffenheim' 'LOSC Lille' 'Deportivo Alavés' 'Burnley'
 'Leeds United' 'Fulham' 'PFC CSKA Moscow' 'Genoa' 'Galatasaray SK'
 'Atlanta United' 'Atlético Mineiro' 'Flamengo' 'Palmeiras' 'No Club'
 'São Paulo' 'West Ham United' 'SD Eibar' 'River Plate' 'OGC Nice'
 'Real Valladolid CF' 'Sporting CP' 'PSV' 'Feyenoord' 'Club Brugge KV'
 'Shakhtar Donetsk' 'Vissel Kobe' 'Boca Juniors' '1. FC Union Berlin'
 'Dalian YiFang FC' 'AS Saint-Étienne' 'Sassuolo' 'Tigres U.A.N.L.'
 'Dinamo Zagreb' 'Dynamo Kyiv' 'Fluminense' 'Udinese' 'Aston Villa'
 'Stade Rennais FC' 'Beşiktaş JK' 'Brighton & Hove Albion'
 'Hebei China Fortune FC' 'Southampton' 'Lokomotiv Moscow'
 'Jiangsu Suning FC' 'Al Hilal' 'West Bromwich Albion' 'Fenerbahçe SK'
 'FC Groningen' 'Guangzhou R&F FC' 'Orlando City SC' 'Sampdoria'
 'Stade de Reims' 'Sheffield United' 'Santos' 'Internacional' 'Coritiba'
 'CA Osasuna' 'LA Galaxy' 'Al Nassr' 'SC Freiburg' 'SC Braga'
 'Olympiacos CFP' 'Toronto FC' 'Granada CF' 'FC Schalke 04'
 'RC Strasbourg Alsace' 'Hertha BSC' 'AZ Alkmaar' 'Seattle Sounders FC'
 'Montpellier HSC' 'Shanghai Greenland Shenhua FC' 'Hamburger SV'
 'Girona FC' 'Racing Club' 'Portland Timbers' 'FC Girondins de Bordeaux'
 'Watford' 'Estudiantes de La Plata' 'Club América' 'Vitória Guimarães'
 'SK Slavia Praha' 'Trabzonspor' 'RCD Espanyol' 'FC Nantes' 'Angers SCO'
 'Cruz Azul' 'BSC Young Boys' 'Club León' 'Spartak Moscow' 'Sivasspor'
 'Elche CF' 'FC Augsburg' 'Wuhan Zall' 'Parma' 'Royal Antwerp FC'
 'Monterrey' 'San Lorenzo de Almagro' 'AC Monza' 'Club Atlético Lanús'
 'SD Huesca' 'Derby County' 'Kayserispor' 'RSC Anderlecht' 'CD Leganés'
 'Vélez Sarsfield' 'Stade Brestois 29' 'Tianjin TEDA FC' 'Birmingham City'
 'Hellas Verona' '1. FC Köln' 'Al Wehda' 'Bournemouth' 'Alanyaspor'
 'Bologna' 'Amiens SC' 'Celtic' 'Shijiazhuang Ever Bright F.C.'
 'Club Atlas' 'Al Ahli' 'Norwich City' 'Fatih Karagümrük S.K.'
 'Club Tijuana' 'Universidad Católica' 'Goiás' 'Benevento' 'Independiente'
 'Qingdao Huanghai F.C.' 'Brentford' 'AEK Athens' 'Racing Club de Lens'
 'Olimpia Asunción' 'Shenzhen FC' 'Çaykur Rizespor' 'KAA Gent'
 'New England Revolution' 'Cádiz CF' '1. FSV Mainz 05' 'Vasco da Gama'
 'FC Midtjylland' 'Al Ain FC' 'Santos Laguna' 'SPAL' 'Perth Glory'
 'FC Utrecht' 'Montreal Impact' 'UD Almería' 'Fortaleza' 'Spezia'
 'FC Basel 1893' 'FC København' 'Godoy Cruz' 'Deportivo Toluca'
 'Nacional de Montevideo' 'Aalborg BK' 'Rio Ave FC' 'FC Metz'
 'Chongqing Dangdai Lifan FC SWM Team' 'Rosenborg BK'
 'FC Red Bull Salzburg' 'Botafogo' 'DSC Arminia Bielefeld'
 'Club Athletico Paranaense' 'RCD Mallorca' 'Pachuca' 'Swansea City'
 'KRC Genk' 'En Avant de Guingamp' 'Lecce' 'Nîmes Olympique' 'Colo-Colo'
 'Stade Malherbe Caen' 'Columbus Crew SC' 'Junior FC' 'VfB Stuttgart'
 'Moreirense FC' 'Rangers FC' 'Malmö FF' 'Shandong Luneng TaiShan FC'
 'Sparta Praha' 'Hatayspor' 'Chicago Fire' 'Toulouse Football Club'
 'FC Seoul' 'Antalyaspor' 'Deportivo Cali' 'Kaizer Chiefs' 'Real Zaragoza'
 'Atlético Clube Goianiense' 'Puebla FC' 'Fortuna Düsseldorf'
 'Western United FC' 'Astra Giurgiu' 'Henan Jianye FC' 'Bahia' 'Famalicão'
 'Atiker Konyaspor' 'Peñarol' 'DC United' 'New York City FC'
 'Argentinos Juniors' 'U.N.A.M.' 'Minnesota United FC' 'Nottingham Forest'
 'Independiente del Valle' 'Defensa y Justicia' 'Philadelphia Union'
 "Newell's Old Boys" 'Rosario Central' 'Atlético de San Luis' 'FC Dallas'
 'Denizlispor' 'Yeni Malatyaspor' 'Club Atlético Colón' 'Houston Dynamo'
 'Millwall' 'Clube Sport Marítimo' 'MKE Ankaragücü' 'Guadalajara'
 'Boavista FC' 'Sporting Kansas City' 'Atlético Nacional' 'CD Lugo'
 'New York Red Bulls' 'PAOK' 'SC Heerenveen' 'Daegu FC'
 'Preston North End' 'Damac FC' 'Brescia' 'VfL Bochum 1848'
 'Vancouver Whitecaps FC' 'SV Sandhausen' 'Royal Excel Mouscron'
 'Dijon FCO' 'Molde FK' 'Panathinaikos FC' 'LASK Linz' 'Ulsan Hyundai FC'
 'Real Salt Lake' 'FC Luzern' 'Viktoria Plzeň' 'Orlando Pirates'
 'Al Ittihad' '1. FC Nürnberg' 'Standard de Liège' 'Rayo Vallecano'
 'Club Libertad' 'Jeonbuk Hyundai Motors' 'Western Sydney Wanderers'
 'Unión de Santa Fe' 'FC Sion' 'Sydney FC' 'Hannover 96'
 'Real Sporting de Gijón' 'FC Cincinnati' 'ESTAC Troyes'
 'San Jose Earthquakes' 'Club Guaraní' 'FC Lorient' 'Gençlerbirliği SK'
 'Sporting de Charleroi' 'Wisła Kraków' 'Al Taawoun' 'Reading'
 'Gazişehir Gaziantep F.K.' 'Blackburn Rovers' 'Kashiwa Reysol'
 'FK Bodø/Glimt' 'Willem II' 'Vitesse' 'Gil Vicente FC' 'SønderjyskE'
 'Yokohama F. Marinos' 'FC St. Gallen' 'Club Atlético Aldosivi'
 'Göztepe SK' 'Holstein Kiel' 'FC Juárez' 'FCSB (Steaua)' 'Ettifaq FC'
 'KAS Eupen' 'FC Tokyo' 'Melbourne City FC' 'Universitatea Craiova'
 'CD Tondela' 'Wolfsberger AC' 'Ceará Sporting Club'
 'River Plate Asunción' 'Stoke City' 'Paris FC' 'IFK Norrköping' 'Crotone'
 'Cardiff City' 'América de Cali' 'Al Faisaly' 'Independiente Medellín'
 'Portimonense SC' 'CD Tenerife' 'Heracles Almelo' 'Nashville SC'
 'SK Rapid Wien' 'Kawasaki Frontale' 'Club Necaxa' 'Chievo Verona'
 'Lech Poznań' 'AIK' 'FK Austria Wien' 'Querétaro' '1. FC Heidenheim 1846'
 'Legia Warszawa' 'Club Atlético Banfield' 'Os Belenenses'
 'Huddersfield Town' 'KSV Cercle Brugge' 'LDU Quito'
 'Gimnasia y Esgrima La Plata' 'Gamba Osaka' 'Middlesbrough' 'Servette FC'
 'Empoli' 'Real Oviedo' 'Kasimpaşa SK' 'CFR Cluj' 'Millonarios FC'
 'FC Paços de Ferreira' 'Sint-Truidense VV' 'AD Alcorcón'
 'Colorado Rapids' 'Dinamo Bucureşti' 'Cerezo Osaka' 'FC Emmen'
 'Sheffield Wednesday' 'FC Erzgebirge Aue' 'Raków Częstochowa'
 'Atlético Tucumán' 'SV Darmstadt 98' 'Bristol City' 'Oud-Heverlee Leuven'
 'Barnsley' 'Queens Park Rangers' 'Sangju Sangmu FC' 'Helsingborgs IF'
 'AC Ajaccio' 'Oceânico FC' 'Club Atlético Talleres' 'Al Hazem'
 'SC Paderborn 07' 'Club Atlético Huracán' 'KV Kortrijk' 'El Nacional'
 'Mazatlán FC' 'Aberdeen' 'CD Mirandés' 'SV Zulte-Waregem' 'Piast Gliwice'
 'Djurgårdens IF' 'Central Córdoba' 'Wellington Phoenix'
 'Deportivo Binacional' 'Patronato' 'SpVgg Greuther Fürth' 'IFK Göteborg'
 'FC Cartagena' 'Santa Clara' 'FC Twente' 'Farense' 'ADO Den Haag'
 'AJ Auxerre' 'Al Fateh' 'Valenciennes FC' 'Hokkaido Consadole Sapporo'
 'FC St. Pauli' 'Albacete BP' '1. FC Kaiserslautern' 'Al Fayha'
 'Incheon United FC' 'KV Mechelen' 'Pohang Steelers' 'CD Nacional'
 'Unión La Calera' 'BB Erzurumspor' 'Kashima Antlers' 'Arsenal de Sarandí'
 'HJK Helsinki' 'Karlsruher SC' 'Aarhus GF' 'FC Zürich'
 'Barcelona Sporting Club' 'SG Dynamo Dresden' 'Sanfrecce Hiroshima'
 'Al Raed' 'SD Ponferradina' 'Brøndby IF' 'Lechia Gdańsk' 'FC Viitorul'
 'SK Sturm Graz' 'IF Elfsborg' 'Gangwon FC' 'Melgar FBC'
 'Club Atlético Grau' 'Jagiellonia Białystok' 'Waasland-Beveren'
 'VfL Osnabrück' 'Nagoya Grampus' 'CF Fuenlabrada' 'Shamrock Rovers'
 'Shimizu S-Pulse' 'RKC Waalwijk' 'Vålerenga Fotball' 'Clermont Foot 63'
 'FC Ingolstadt 04' 'FC Würzburger Kickers' 'Górnik Zabrze'
 'Charlton Athletic' 'Beerschot AC' 'Coquimbo Unido' 'Viktoria Köln'
 'Hull City' 'Málaga CF' 'FC Nordsjælland' 'UD Las Palmas' 'VVV-Venlo'
 'GwangJu FC' 'Chamois Niortais Football Club' 'FC Lugano' 'Cusco FC'
 'Sparta Rotterdam' 'Sol de América' 'PEC Zwolle' 'Pogoń Szczecin'
 'Doncaster Rovers' 'Kristiansund BK' 'Liverpool Fútbol Club'
 'Club Bolívar' 'Urawa Red Diamonds' 'SK Brann' 'Eintracht Braunschweig'
 'Nacional Asunción' 'Melbourne Victory' 'Kilmarnock' 'Dundalk'
 'SSV Jahn Regensburg' 'Abha Club' 'Club Atlético Tigre'
 'Suwon Samsung Bluewings' 'Shonan Bellmare' 'SD Aucas' 'Emelec'
 'Fortuna Sittard' 'La Berrichonne de Châteauroux' 'Śląsk Wrocław'
 'Coventry City' 'Sunderland' 'Alianza Lima' 'Hammarby IF' 'Cracovia'
 'CE Sabadell FC' 'Oita Trinita' 'BK Häcken' 'Luton Town' 'Le Havre AC'
 'IK Sirius' 'Zagłębie Lubin' 'Grenoble Foot 38' 'Macarthur FC'
 'Rodez Aveyron Football' 'Vegalta Sendai' 'Motherwell'
 'SV Wehen Wiesbaden' 'Audax Italiano' 'Gaz Metan Mediaş' 'Portsmouth'
 'Hibernian' 'Always Ready' 'UD Logroñés' 'FC Voluntari' 'FC Hermannstadt'
 'AS Nancy Lorraine' 'Rotherham United' 'Fleetwood Town'
 'Jorge Wilstermann' 'Odense Boldklub' 'MSV Duisburg'
 'FC Sochaux-Montbéliard' 'Milton Keynes Dons' 'River Plate Montevideo'
 'Delfín SC' 'Universidad Católica del Ecuador' 'Deportivo Pasto'
 'KV Oostende' 'Club Plaza Colonia' 'Wigan Athletic' 'FC Botoşani'
 'C.D. Castellón' 'SCR Altach' 'Örebro SK' 'TSV Hartberg' 'Stabæk Fotball'
 'Wycombe Wanderers' 'St. Johnstone FC' 'Oxford United' 'Lincoln City'
 'Randers FC' 'Viking FK' 'FC Chambly Oise' 'Dundee United'
 'Oriente Petrolero' 'Odds BK' 'Nacional Potosí' 'Sepsi OSK'
 'FC Hansa Rostock' 'Lyngby BK' 'SpVgg Unterhaching' 'Brisbane Roar'
 'Seongnam FC' 'SV Ried' 'CD Huachipato' 'WSG Tirol'
 'Podbeskidzie Bielsko-Biała' 'Peterborough United' 'Club Blooming'
 'Wisła Płock' 'Busan IPark' 'FSV Zwickau' 'Mjøndalen IF' 'Vejle Boldklub'
 'Pau FC' 'FC Lausanne-Sport' 'Estudiantes de Mérida' 'Sagan Tosu'
 'SV Waldhof Mannheim' 'Sport Huancayo' 'Hallescher FC' 'Kalmar FF'
 'St. Mirren' 'SKN St. Pölten' 'Sarpsborg 08 FF' 'Shrewsbury'
 'TSV 1860 München' 'SV Meppen' 'Ipswich Town' 'IK Start'
 'Adelaide United' 'Stal Mielec' 'Centro Atlético Fénix' 'Newcastle Jets'
 'Livingston FC' 'AC Mineros de Guayana' 'AFC Wimbledon' 'Burton Albion'
 'Al Adalah' 'Warta Poznań' 'USL Dunkerque' 'Bristol Rovers' 'UTA Arad'
 'Östersunds FK' 'Sportivo Luqueño' 'Politehnica Iaşi' 'Salford City'
 'Central Coast Mariners' 'Caracas FC' 'AC Horsens' 'Plymouth Argyle'
 'Aalesunds FK' 'Crewe Alexandra' 'Chindia Târgovişte' 'Oldham Athletic'
 'Yokohama FC' 'Blackpool' 'Northampton Town' 'Bayern München II'
 'FK Haugesund' 'KFC Uerdingen 05' 'Forest Green Rovers' 'Cheltenham Town'
 'Strømsgodset IF' 'Mjällby AIF' 'Exeter City' 'Cambridge United'
 'Grimsby Town' 'FC Vaduz' 'Türkgücü München' 'VfB Lübeck'
 'Bolton Wanderers' 'Bradford City' '1. FC Magdeburg'
 'FC Admira Wacker Mödling' 'Hamilton Academical FC' 'Aragua FC'
 'Accrington Stanley' 'Swindon Town' 'Carlisle United' 'FC Argeș'
 'Port Vale' 'Academica Clinceni' 'Rochdale' 'Gillingham'
 'Tranmere Rovers' 'Southend United' '1. FC Saarbrücken'
 'Colchester United' 'Mansfield Town' 'Falkenbergs FF' 'SC Verl'
 'Varbergs BoIS' 'Crawley Town' 'Sandefjord Fotball' 'Newport County'
 'Bohemian FC' 'Ross County FC' 'Scunthorpe United' 'Morecambe' 'Walsall'
 'Leyton Orient' 'Stevenage' 'Barrow' 'Derry City' 'Llaneros de Guanare'
 'Sligo Rovers' 'Zamora FC' "St. Patrick's Athletic" 'Cork City'
 'Shelbourne FC' 'Harrogate Town' 'Waterford FC' 'Finn Harps']


Contract
['2004 ~ 2021' '2018 ~ 2022' '2014 ~ 2023' '2015 ~ 2023' '2017 ~ 2022'
 '2017 ~ 2023' '2018 ~ 2024' '2014 ~ 2022' '2018 ~ 2023' '2016 ~ 2023'
 '2013 ~ 2023' '2011 ~ 2023' '2009 ~ 2022' '2005 ~ 2021' '2011 ~ 2021'
 '2015 ~ 2022' '2017 ~ 2024' '2010 ~ 2024' '2012 ~ 2021' '2019 ~ 2024'
 '2015 ~ 2024' '2017 ~ 2025' '2020 ~ 2025' '2019 ~ 2023' '2008 ~ 2023'
 '2015 ~ 2021' '2020 ~ 2022' '2012 ~ 2022' '2016 ~ 2025' '2013 ~ 2022'
 '2011 ~ 2022' '2012 ~ 2024' '2016 ~ 2021' '2012 ~ 2023' '2008 ~ 2022'
 '2019 ~ 2022' '2017 ~ 2021' '2013 ~ 2024' '2020 ~ 2024' '2010 ~ 2022'
 '2020 ~ 2021' '2011 ~ 2024' '2020 ~ 2023' '2014 ~ 2024' '2013 ~ 2026'
 '2016 ~ 2022' '2010 ~ 2021' '2013 ~ 2021' '2019 ~ 2025' '2018 ~ 2025'
 '2016 ~ 2024' '2018 ~ 2021' '2009 ~ 2024' '2007 ~ 2022'
 'Jun 30, 2021 On Loan' '2009 ~ 2021' '2019 ~ 2021' '2019 ~ 2026' 'Free'
 '2012 ~ 2028' '2010 ~ 2023' '2014 ~ 2021' '2015 ~ 2025' '2014 ~ 2026'
 '2012 ~ 2025' '2017 ~ 2020' '2002 ~ 2022' '2020 ~ 2027' '2013 ~ 2025'
 'Dec 31, 2020 On Loan' '2019 ~ 2020' '2011 ~ 2025' '2016 ~ 2020'
 '2007 ~ 2021' '2020 ~ 2026' '2010 ~ 2025' '2009 ~ 2023' '2008 ~ 2021'
 '2020 ~ 2020' '2016 ~ 2026' 'Jan 30, 2021 On Loan' '2012 ~ 2020'
 '2014 ~ 2025' 'Jun 30, 2022 On Loan' '2015 ~ 2020' 'May 31, 2021 On Loan'
 '2018 ~ 2020' '2014 ~ 2020' '2013 ~ 2020' '2006 ~ 2024'
 'Jul 5, 2021 On Loan' 'Dec 31, 2021 On Loan' '2004 ~ 2025' '2011 ~ 2020'
 'Jul 1, 2021 On Loan' 'Jan 1, 2021 On Loan' '2006 ~ 2023'
 'Aug 31, 2021 On Loan' '2006 ~ 2021' '2005 ~ 2023' '2003 ~ 2020'
 '2009 ~ 2020' '2002 ~ 2020' '2005 ~ 2020' '2005 ~ 2022'
 'Jan 31, 2021 On Loan' '2010 ~ 2020' 'Dec 30, 2021 On Loan' '2008 ~ 2020'
 '2007 ~ 2020' '2003 ~ 2021' 'Jun 23, 2021 On Loan' 'Jan 3, 2021 On Loan'
 'Nov 27, 2021 On Loan' '2002 ~ 2021' 'Jan 17, 2021 On Loan'
 'Jun 30, 2023 On Loan' '1998 ~ 2021' '2003 ~ 2022' '2007 ~ 2023'
 'Jul 31, 2021 On Loan' 'Nov 22, 2020 On Loan' 'May 31, 2022 On Loan'
 '2006 ~ 2020' 'Dec 30, 2020 On Loan' '2007 ~ 2025' 'Jan 4, 2021 On Loan'
 'Nov 30, 2020 On Loan' '2004 ~ 2020' '2009 ~ 2025' 'Aug 1, 2021 On Loan']


Positions
['RW, ST, CF' 'ST, LW' 'GK' 'CAM, CM' 'LW, CAM' 'ST' 'RW' 'ST, LW, RW'
 'CB' 'LW' 'CDM' 'CF, ST' 'LW, RW' 'CDM, CM' 'CDM, RB' 'CF, CAM' 'LW, ST'
 'CM' 'ST, CF, LW' 'RM, LM, CAM' 'RB' 'RW, CAM, CM' 'LB' 'LM, CF' 'CF'
 'RW, LW' 'CAM, RM, RW' 'CM, CDM' 'CAM, CF, ST' 'CM, CDM, CAM'
 'CF, LW, CAM' 'CAM, RM, CF' 'LM, ST' 'RM, LM, RW' 'LM' 'CAM, RW'
 'CB, CDM' 'RW, RM' 'LW, CF' 'CM, RM, LM' 'LB, LM' 'CAM, CM, RM'
 'CAM, CM, CF' 'CAM, CF' 'LM, RM, LW' 'LM, LB, CM' 'CM, LM, LB' 'RM, RW'
 'RM, CM' 'CAM, CM, LW' 'CB, LB' 'RM, RB' 'ST, RW' 'LM, RW, LW' 'RB, LB'
 'RB, RM' 'RM' 'LM, RM, CF' 'CAM, RM' 'RB, RWB' 'CDM, CB, CM'
 'CAM, RM, ST' 'LM, LW, RM' 'CM, CAM' 'ST, RM, CF' 'LM, RM' 'RM, CF'
 'LM, LWB' 'RW, RM, CF' 'RB, CM' 'LW, CAM, RW' 'CAM, LW, CM'
 'CM, CAM, CDM' 'RW, LW, CAM' 'CM, CAM, LM' 'CM, RM, ST' 'CDM, CM, RB'
 'ST, CAM' 'CAM, LW, ST' 'LB, CB, LWB' 'RM, ST' 'CB, CDM, LB' 'RWB, RM'
 'CM, LM, RM' 'RB, CDM, CM' 'RW, LW, RM' 'LM, LW' 'CM, LM' 'LM, LB'
 'RM, LM, CF' 'LB, LM, RM' 'CDM, CM, CAM' 'ST, LW, RM' 'CAM, CM, ST'
 'ST, CF' 'LWB, LB' 'LW, RW, LM' 'RM, RW, ST' 'LWB' 'CF, ST, CAM'
 'LM, CAM, RM' 'RB, CB' 'ST, LM' 'RW, CAM' 'LM, CAM' 'RWB, RB'
 'ST, RW, LW' 'CAM' 'RB, RM, RW' 'LB, LWB' 'RM, CAM' 'CAM, ST' 'CDM, CB'
 'CF, LM, LW' 'CAM, LM, LW' 'LW, RW, CAM' 'CB, RB' 'RB, CB, RWB'
 'LM, LW, ST' 'LW, ST, CM' 'RM, CAM, CM' 'CB, RB, RWB' 'RW, ST, LW'
 'LW, CAM, CM' 'CM, LM, CDM' 'LB, LM, LWB' 'CB, LB, RB' 'CAM, LW'
 'RWB, RB, RM' 'CF, CAM, ST' 'RM, CAM, RW' 'RW, ST' 'LW, LM' 'RB, RM, CM'
 'ST, CAM, RW' 'CM, RB, LB' 'CAM, LM, RM' 'RB, RW' 'LM, CM' 'RM, LM, CM'
 'CDM, CM, CB' 'CM, CF' 'CF, LW, RW' 'ST, RM' 'CAM, CM, CDM' 'LB, CB'
 'RW, RWB' 'ST, LM, RM' 'RM, RWB, RB' 'LM, ST, CAM' 'CAM, ST, CF' 'LW, CM'
 'RB, RWB, LB' 'RM, LM' 'CM, CAM, RM' 'ST, LW, CAM' 'RM, RW, CAM'
 'CM, CDM, RM' 'RB, RM, RWB' 'CDM, CB, LB' 'CAM, ST, LM' 'LM, CM, RM'
 'CF, RW' 'CAM, RM, LW' 'CM, RM, CDM' 'LB, LWB, LM' 'LW, RW, CF'
 'LW, LM, CAM' 'LWB, LW, LB' 'CDM, CM, LM' 'CB, CM' 'RWB, RW, RB'
 'ST, RW, RM' 'LW, RW, CM' 'LM, RM, CAM' 'LB, RB' 'RWB, RM, RB'
 'LM, RB, LB' 'LW, LM, ST' 'ST, RM, LM' 'CAM, CM, LM' 'CF, CM'
 'LW, ST, RW' 'ST, CAM, CF' 'LB, CB, LM' 'CM, CDM, LM' 'RM, RWB'
 'LB, LM, RB' 'RB, LB, CB' 'CM, CDM, RB' 'LB, CM' 'CF, CAM, LW' 'RM, LWB'
 'CF, ST, LM' 'LB, RB, CB' 'LW, CF, ST' 'RM, ST, CAM' 'LW, RW, ST'
 'ST, LW, LM' 'CM, LW' 'CDM, CM, LB' 'CM, RM, CAM' 'ST, CF, CAM'
 'CM, LM, CAM' 'RWB' 'LM, ST, RM' 'CAM, RM, CM' 'CAM, LM, CM' 'RW, LW, ST'
 'CAM, RM, LM' 'CF, ST, LW' 'LWB, LB, LM' 'RM, CM, CAM' 'LB, LM, CAM'
 'CAM, CDM' 'RW, RB, RM' 'RM, ST, RW' 'CM, CAM, LW' 'CF, ST, RW'
 'LM, RM, RB' 'LM, RM, CM' 'CB, RB, RM' 'RB, CDM' 'RM, ST, LM'
 'LB, LWB, CB' 'CDM, LB' 'LM, RM, ST' 'RWB, RB, LWB' 'ST, LM, CAM'
 'ST, RM, CAM' 'RB, RWB, RM' 'CF, LM, CAM' 'CAM, CF, RW' 'RB, RM, LB'
 'CDM, RWB' 'CM, RW, CAM' 'ST, CF, LM' 'RM, LM, RWB' 'RB, LB, RM'
 'LM, LW, LB' 'RM, LM, ST' 'CAM, LM' 'ST, LM, LW' 'LW, RW, RM' 'CF, LW'
 'LB, CM, RB' 'RB, CB, CDM' 'CB, RB, LB' 'CAM, RW, RM' 'LWB, LM'
 'LW, CF, LM' 'CAM, CF, CM' 'LWB, CB' 'CM, CDM, LW' 'LM, CM, LB' 'CM, RM'
 'RW, LW, CF' 'CM, CDM, CB' 'LM, RM, RW' 'RM, RW, LM' 'RM, CAM, LM'
 'LWB, RM, LB' 'RM, LB, RB' 'CM, CF, RM' 'RM, RB, LB' 'ST, LM, RW'
 'CAM, ST, LW' 'CF, LW, ST' 'LM, LW, CAM' 'RM, RW, CF' 'LW, LM, CF'
 'CM, RW, LW' 'LM, CM, CAM' 'CAM, RW, ST' 'CM, CAM, CF' 'RW, LWB, LW'
 'CB, RB, CDM' 'RW, RM, LW' 'LW, ST, LM' 'RWB, RW' 'ST, CAM, LM' 'CM, CB'
 'RM, RW, CM' 'LWB, CM' 'RM, LM, LB' 'RM, CAM, ST' 'CDM, RM, RB'
 'LM, LB, RB' 'LB, RB, RWB' 'RM, RWB, CAM' 'CAM, LM, CF' 'LM, CAM, CM'
 'CF, CAM, RW' 'CDM, CM, RM' 'CF, CAM, CM' 'ST, RM, LW' 'CB, CDM, CM'
 'RB, RW, LB' 'ST, RW, CAM' 'CM, LB' 'LW, RM, RW' 'CM, RM, RW'

# Data Treatment

## Dealing with inconsistent data format

These are some columns that have inconsistent data format:

1.   Club
2.   Height
2.   Weight
3.   Joined
5.   Value
6.   Wage
7.   Release Clause
8.   W/S
9.   SM
10.  IR
4.   Loan Date End
10.  Contract

### Data['Club']

In [87]:
data['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sinobo Guoan FC', 'Getafe CF', 'SV Werder Bremen',
       'TSG 1899 Hoffenheim', 'LOSC Lille', 'Deportivo Alavés', 'Burnley',
       'Leeds United', 'Fulham', 'PFC CSKA Moscow', 'Genoa',
       'Galatasaray SK', 'Atlanta United', 'Atlético Mineiro', 'Flamengo',
       'Palmeiras', 'No Club', 'São Paulo', 'West Ham United', 'SD Eibar',
       'River Plate', 'OGC Nice', 'Real Valladolid CF', 'Sporting CP',
       'PSV', 'Feyenoord', 'Club Brugge KV', 'Shakhtar Donetsk',
       'Vissel Kobe', 'Boca Juniors', '1. FC Union Berlin',
       'Dalian YiFang FC', 'AS Saint-Étienne', 'Sassuolo',
       'Tigres U.A.N.L.', 'Dinamo Zagreb', 'Dynamo Kyiv', 'Fluminense',
       'Udinese', 'Aston Villa', 'Stade Rennais FC', 'Beşiktaş JK',
       'Brighton & Hove Albion', 'Hebei China Fortune FC', 'Southampton',
       'Lokomotiv Moscow', 'Jiangsu Suning FC', 'Al Hilal',
       'West Bromwich Albion', 'Fenerbahçe SK', 'FC Groningen',
       'Guangzhou R&F FC', 'Orlando City SC', 'Sampdoria',
       'Stade de Reims', 'Sheffield United', 'Santos', 'Internacional',
       'Coritiba', 'CA Osasuna', 'LA Galaxy', 'Al Nassr', 'SC Freiburg',
       'SC Braga', 'Olympiacos CFP', 'Toronto FC', 'Granada CF',
       'FC Schalke 04', 'RC Strasbourg Alsace', 'Hertha BSC',
       'AZ Alkmaar', 'Seattle Sounders FC', 'Montpellier HSC',
       'Shanghai Greenland Shenhua FC', 'Hamburger SV', 'Girona FC',
       'Racing Club', 'Portland Timbers', 'FC Girondins de Bordeaux',
       'Watford', 'Estudiantes de La Plata', 'Club América',
       'Vitória Guimarães', 'SK Slavia Praha', 'Trabzonspor',
       'RCD Espanyol', 'FC Nantes', 'Angers SCO', 'Cruz Azul',
       'BSC Young Boys', 'Club León', 'Spartak Moscow', 'Sivasspor',
       'Elche CF', 'FC Augsburg', 'Wuhan Zall', 'Parma',
       'Royal Antwerp FC', 'Monterrey', 'San Lorenzo de Almagro',
       'AC Monza', 'Club Atlético Lanús', 'SD Huesca', 'Derby County',
       'Kayserispor', 'RSC Anderlecht', 'CD Leganés', 'Vélez Sarsfield',
       'Stade Brestois 29', 'Tianjin TEDA FC', 'Birmingham City',
       'Hellas Verona', '1. FC Köln', 'Al Wehda', 'Bournemouth',
       'Alanyaspor', 'Bologna', 'Amiens SC', 'Celtic',
       'Shijiazhuang Ever Bright F.C.', 'Club Atlas', 'Al Ahli',
       'Norwich City', 'Fatih Karagümrük S.K.', 'Club Tijuana',
       'Universidad Católica', 'Goiás', 'Benevento', 'Independiente',
       'Qingdao Huanghai F.C.', 'Brentford', 'AEK Athens',
       'Racing Club de Lens', 'Olimpia Asunción', 'Shenzhen FC',
       'Çaykur Rizespor', 'KAA Gent', 'New England Revolution',
       'Cádiz CF', '1. FSV Mainz 05', 'Vasco da Gama', 'FC Midtjylland',
       'Al Ain FC', 'Santos Laguna', 'SPAL', 'Perth Glory', 'FC Utrecht',
       'Montreal Impact', 'UD Almería', 'Fortaleza', 'Spezia',
       'FC Basel 1893', 'FC København', 'Godoy Cruz', 'Deportivo Toluca',
       'Nacional de Montevideo', 'Aalborg BK', 'Rio Ave FC', 'FC Metz',
       'Chongqing Dangdai Lifan FC SWM Team', 'Rosenborg BK',
       'FC Red Bull Salzburg', 'Botafogo', 'DSC Arminia Bielefeld',
       'Club Athletico Paranaense', 'RCD Mallorca', 'Pachuca',
       'Swansea City', 'KRC Genk', 'En Avant de Guingamp', 'Lecce',
       'Nîmes Olympique', 'Colo-Colo', 'Stade Malherbe Caen',
       'Columbus Crew SC', 'Junior FC', 'VfB Stuttgart', 'Moreirense FC',
       'Rangers FC', 'Malmö FF', 'Shandong Luneng TaiShan FC',
       'Sparta Praha', 'Hatayspor', 'Chicago Fire',
       'Toulouse Football Club', 'FC Seoul', 'Antalyaspor',
       'Deportivo Cali', 'Kaizer Chiefs', 'Real Zaragoza',
       'Atlético Clube Goianiense', 'Puebla FC', 'Fortuna Düsseldorf',
       'Western United FC', 'Astra Giurgiu', 'Henan Jianye FC', 'Bahia',
       'Famalicão', 'Atiker Konyaspor', 'Peñarol', 'DC United',
       'New York City FC', 'Argentinos Juniors', 'U.N.A.M.',
       'Minnesota United FC', 'Nottingham Forest',
       'Independiente del Valle', 'Defensa y Justicia',
       'Philadelphia Union', "Newell's Old Boys", 'Rosario Central',
       'Atlético de San Luis', 'FC Dallas', 'Denizlispor',
       'Yeni Malatyaspor', 'Club Atlético Colón', 'Houston Dynamo',
       'Millwall', 'Clube Sport Marítimo', 'MKE Ankaragücü',
       'Guadalajara', 'Boavista FC', 'Sporting Kansas City',
       'Atlético Nacional', 'CD Lugo', 'New York Red Bulls', 'PAOK',
       'SC Heerenveen', 'Daegu FC', 'Preston North End', 'Damac FC',
       'Brescia', 'VfL Bochum 1848', 'Vancouver Whitecaps FC',
       'SV Sandhausen', 'Royal Excel Mouscron', 'Dijon FCO', 'Molde FK',
       'Panathinaikos FC', 'LASK Linz', 'Ulsan Hyundai FC',
       'Real Salt Lake', 'FC Luzern', 'Viktoria Plzeň', 'Orlando Pirates',
       'Al Ittihad', '1. FC Nürnberg', 'Standard de Liège',
       'Rayo Vallecano', 'Club Libertad', 'Jeonbuk Hyundai Motors',
       'Western Sydney Wanderers', 'Unión de Santa Fe', 'FC Sion',
       'Sydney FC', 'Hannover 96', 'Real Sporting de Gijón',
       'FC Cincinnati', 'ESTAC Troyes', 'San Jose Earthquakes',
       'Club Guaraní', 'FC Lorient', 'Gençlerbirliği SK',
       'Sporting de Charleroi', 'Wisła Kraków', 'Al Taawoun', 'Reading',
       'Gazişehir Gaziantep F.K.', 'Blackburn Rovers', 'Kashiwa Reysol',
       'FK Bodø/Glimt', 'Willem II', 'Vitesse', 'Gil Vicente FC',
       'SønderjyskE', 'Yokohama F. Marinos', 'FC St. Gallen',
       'Club Atlético Aldosivi', 'Göztepe SK', 'Holstein Kiel',
       'FC Juárez', 'FCSB (Steaua)', 'Ettifaq FC', 'KAS Eupen',
       'FC Tokyo', 'Melbourne City FC', 'Universitatea Craiova',
       'CD Tondela', 'Wolfsberger AC', 'Ceará Sporting Club',
       'River Plate Asunción', 'Stoke City', 'Paris FC', 'IFK Norrköping',
       'Crotone', 'Cardiff City', 'América de Cali', 'Al Faisaly',
       'Independiente Medellín', 'Portimonense SC', 'CD Tenerife',
       'Heracles Almelo', 'Nashville SC', 'SK Rapid Wien',
       'Kawasaki Frontale', 'Club Necaxa', 'Chievo Verona', 'Lech Poznań',
       'AIK', 'FK Austria Wien', 'Querétaro', '1. FC Heidenheim 1846',
       'Legia Warszawa', 'Club Atlético Banfield', 'Os Belenenses',
       'Huddersfield Town', 'KSV Cercle Brugge', 'LDU Quito',
       'Gimnasia y Esgrima La Plata', 'Gamba Osaka', 'Middlesbrough',
       'Servette FC', 'Empoli', 'Real Oviedo', 'Kasimpaşa SK', 'CFR Cluj',
       'Millonarios FC', 'FC Paços de Ferreira', 'Sint-Truidense VV',
       'AD Alcorcón', 'Colorado Rapids', 'Dinamo Bucureşti',
       'Cerezo Osaka', 'FC Emmen', 'Sheffield Wednesday',
       'FC Erzgebirge Aue', 'Raków Częstochowa', 'Atlético Tucumán',
       'SV Darmstadt 98', 'Bristol City', 'Oud-Heverlee Leuven',
       'Barnsley', 'Queens Park Rangers', 'Sangju Sangmu FC',
       'Helsingborgs IF', 'AC Ajaccio', 'Oceânico FC',
       'Club Atlético Talleres', 'Al Hazem', 'SC Paderborn 07',
       'Club Atlético Huracán', 'KV Kortrijk', 'El Nacional',
       'Mazatlán FC', 'Aberdeen', 'CD Mirandés', 'SV Zulte-Waregem',
       'Piast Gliwice', 'Djurgårdens IF', 'Central Córdoba',
       'Wellington Phoenix', 'Deportivo Binacional', 'Patronato',
       'SpVgg Greuther Fürth', 'IFK Göteborg', 'FC Cartagena',
       'Santa Clara', 'FC Twente', 'Farense', 'ADO Den Haag',
       'AJ Auxerre', 'Al Fateh', 'Valenciennes FC',
       'Hokkaido Consadole Sapporo', 'FC St. Pauli', 'Albacete BP',
       '1. FC Kaiserslautern', 'Al Fayha', 'Incheon United FC',
       'KV Mechelen', 'Pohang Steelers', 'CD Nacional', 'Unión La Calera',
       'BB Erzurumspor', 'Kashima Antlers', 'Arsenal de Sarandí',
       'HJK Helsinki', 'Karlsruher SC', 'Aarhus GF', 'FC Zürich',
       'Barcelona Sporting Club', 'SG Dynamo Dresden',
       'Sanfrecce Hiroshima', 'Al Raed', 'SD Ponferradina', 'Brøndby IF',
       'Lechia Gdańsk', 'FC Viitorul', 'SK Sturm Graz', 'IF Elfsborg',
       'Gangwon FC', 'Melgar FBC', 'Club Atlético Grau',
       'Jagiellonia Białystok', 'Waasland-Beveren', 'VfL Osnabrück',
       'Nagoya Grampus', 'CF Fuenlabrada', 'Shamrock Rovers',
       'Shimizu S-Pulse', 'RKC Waalwijk', 'Vålerenga Fotball',
       'Clermont Foot 63', 'FC Ingolstadt 04', 'FC Würzburger Kickers',
       'Górnik Zabrze', 'Charlton Athletic', 'Beerschot AC',
       'Coquimbo Unido', 'Viktoria Köln', 'Hull City', 'Málaga CF',
       'FC Nordsjælland', 'UD Las Palmas', 'VVV-Venlo', 'GwangJu FC',
       'Chamois Niortais Football Club', 'FC Lugano', 'Cusco FC',
       'Sparta Rotterdam', 'Sol de América', 'PEC Zwolle',
       'Pogoń Szczecin', 'Doncaster Rovers', 'Kristiansund BK',
       'Liverpool Fútbol Club', 'Club Bolívar', 'Urawa Red Diamonds',
       'SK Brann', 'Eintracht Braunschweig', 'Nacional Asunción',
       'Melbourne Victory', 'Kilmarnock', 'Dundalk',
       'SSV Jahn Regensburg', 'Abha Club', 'Club Atlético Tigre',
       'Suwon Samsung Bluewings', 'Shonan Bellmare', 'SD Aucas', 'Emelec',
       'Fortuna Sittard', 'La Berrichonne de Châteauroux',
       'Śląsk Wrocław', 'Coventry City', 'Sunderland', 'Alianza Lima',
       'Hammarby IF', 'Cracovia', 'CE Sabadell FC', 'Oita Trinita',
       'BK Häcken', 'Luton Town', 'Le Havre AC', 'IK Sirius',
       'Zagłębie Lubin', 'Grenoble Foot 38', 'Macarthur FC',
       'Rodez Aveyron Football', 'Vegalta Sendai', 'Motherwell',
       'SV Wehen Wiesbaden', 'Audax Italiano', 'Gaz Metan Mediaş',
       'Portsmouth', 'Hibernian', 'Always Ready', 'UD Logroñés',
       'FC Voluntari', 'FC Hermannstadt', 'AS Nancy Lorraine',
       'Rotherham United', 'Fleetwood Town', 'Jorge Wilstermann',
       'Odense Boldklub', 'MSV Duisburg', 'FC Sochaux-Montbéliard',
       'Milton Keynes Dons', 'River Plate Montevideo', 'Delfín SC',
       'Universidad Católica del Ecuador', 'Deportivo Pasto',
       'KV Oostende', 'Club Plaza Colonia', 'Wigan Athletic',
       'FC Botoşani', 'C.D. Castellón', 'SCR Altach', 'Örebro SK',
       'TSV Hartberg', 'Stabæk Fotball', 'Wycombe Wanderers',
       'St. Johnstone FC', 'Oxford United', 'Lincoln City', 'Randers FC',
       'Viking FK', 'FC Chambly Oise', 'Dundee United',
       'Oriente Petrolero', 'Odds BK', 'Nacional Potosí', 'Sepsi OSK',
       'FC Hansa Rostock', 'Lyngby BK', 'SpVgg Unterhaching',
       'Brisbane Roar', 'Seongnam FC', 'SV Ried', 'CD Huachipato',
       'WSG Tirol', 'Podbeskidzie Bielsko-Biała', 'Peterborough United',
       'Club Blooming', 'Wisła Płock', 'Busan IPark', 'FSV Zwickau',
       'Mjøndalen IF', 'Vejle Boldklub', 'Pau FC', 'FC Lausanne-Sport',
       'Estudiantes de Mérida', 'Sagan Tosu', 'SV Waldhof Mannheim',
       'Sport Huancayo', 'Hallescher FC', 'Kalmar FF', 'St. Mirren',
       'SKN St. Pölten', 'Sarpsborg 08 FF', 'Shrewsbury',
       'TSV 1860 München', 'SV Meppen', 'Ipswich Town', 'IK Start',
       'Adelaide United', 'Stal Mielec', 'Centro Atlético Fénix',
       'Newcastle Jets', 'Livingston FC', 'AC Mineros de Guayana',
       'AFC Wimbledon', 'Burton Albion', 'Al Adalah', 'Warta Poznań',
       'USL Dunkerque', 'Bristol Rovers', 'UTA Arad', 'Östersunds FK',
       'Sportivo Luqueño', 'Politehnica Iaşi', 'Salford City',
       'Central Coast Mariners', 'Caracas FC', 'AC Horsens',
       'Plymouth Argyle', 'Aalesunds FK', 'Crewe Alexandra',
       'Chindia Târgovişte', 'Oldham Athletic', 'Yokohama FC',
       'Blackpool', 'Northampton Town', 'Bayern München II',
       'FK Haugesund', 'KFC Uerdingen 05', 'Forest Green Rovers',
       'Cheltenham Town', 'Strømsgodset IF', 'Mjällby AIF', 'Exeter City',
       'Cambridge United', 'Grimsby Town', 'FC Vaduz', 'Türkgücü München',
       'VfB Lübeck', 'Bolton Wanderers', 'Bradford City',
       '1. FC Magdeburg', 'FC Admira Wacker Mödling',
       'Hamilton Academical FC', 'Aragua FC', 'Accrington Stanley',
       'Swindon Town', 'Carlisle United', 'FC Argeș', 'Port Vale',
       'Academica Clinceni', 'Rochdale', 'Gillingham', 'Tranmere Rovers',
       'Southend United', '1. FC Saarbrücken', 'Colchester United',
       'Mansfield Town', 'Falkenbergs FF', 'SC Verl', 'Varbergs BoIS',
       'Crawley Town', 'Sandefjord Fotball', 'Newport County',
       'Bohemian FC', 'Ross County FC', 'Scunthorpe United', 'Morecambe',
       'Walsall', 'Leyton Orient', 'Stevenage', 'Barrow', 'Derry City',
       'Llaneros de Guanare', 'Sligo Rovers', 'Zamora FC',
       "St. Patrick's Athletic", 'Cork City', 'Shelbourne FC',
       'Harrogate Town', 'Waterford FC', 'Finn Harps'], dtype=object)

There are some clubs that have number before the club name. We replace it so the format are uniform

In [88]:
data['Club'] = data['Club'].str.replace("1. ","")
data['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sinobo Guoan FC', 'Getafe CF', 'SV Werder Bremen',
       'TSG 1899 Hoffenheim', 'LOSC Lille', 'Deportivo Alavés', 'Burnley',
       'Leeds United', 'Fulham', 'PFC CSKA Moscow', 'Genoa',
       'Galatasaray SK', 'Atlanta United', 'Atlético Mineiro', 'Flamengo',
       'Palmeiras', 'No Club', 'São Paulo', 'West Ham United', 'SD Eibar',
       'River Plate', 'OGC Nice', 'Real Valladolid CF', 'Sporting CP',
       'PSV', 'Feyenoord', 'Club Brugge KV', 'Shakhtar Donetsk',
       'Vissel Kobe', 'Boca Juniors', 'FC Union Berlin',
       'Dalian YiFang FC', 'AS Saint-Étienne', 'Sassuolo',
       'Tigres U.A.N.L.', 'Dinamo Zagreb', 'Dynamo Kyiv', 'Fluminense',
       'Udinese', 'Aston Villa', 'Stade Rennais FC', 'Beşiktaş JK',
       'Brighton & Hove Albion', 'Hebei China Fortune FC', 'Southampton',
       'Lokomotiv Moscow', 'Jiangsu Suning FC', 'Al Hilal',
       'West Bromwich Albion', 'Fenerbahçe SK', 'FC Groningen',
       'Guangzhou R&F FC', 'Orlando City SC', 'Sampdoria',
       'Stade de Reims', 'Sheffield United', 'Santos', 'Internacional',
       'Coritiba', 'CA Osasuna', 'LA Galaxy', 'Al Nassr', 'SC Freiburg',
       'SC Braga', 'Olympiacos CFP', 'Toronto FC', 'Granada CF',
       'FC Schalke 04', 'RC Strasbourg Alsace', 'Hertha BSC',
       'AZ Alkmaar', 'Seattle Sounders FC', 'Montpellier HSC',
       'Shanghai Greenland Shenhua FC', 'Hamburger SV', 'Girona FC',
       'Racing Club', 'Portland Timbers', 'FC Girondins de Bordeaux',
       'Watford', 'Estudiantes de La Plata', 'Club América',
       'Vitória Guimarães', 'SK Slavia Praha', 'Trabzonspor',
       'RCD Espanyol', 'FC Nantes', 'Angers SCO', 'Cruz Azul',
       'BSC Young Boys', 'Club León', 'Spartak Moscow', 'Sivasspor',
       'Elche CF', 'FC Augsburg', 'Wuhan Zall', 'Parma',
       'Royal Antwerp FC', 'Monterrey', 'San Lorenzo de Almagro',
       'AC Monza', 'Club Atlético Lanús', 'SD Huesca', 'Derby County',
       'Kayserispor', 'RSC Anderlecht', 'CD Leganés', 'Vélez Sarsfield',
       'Stade Brestois 29', 'Tianjin TEDA FC', 'Birmingham City',
       'Hellas Verona', 'FC Köln', 'Al Wehda', 'Bournemouth',
       'Alanyaspor', 'Bologna', 'Amiens SC', 'Celtic',
       'Shijiazhuang Ever Bright F.C.', 'Club Atlas', 'Al Ahli',
       'Norwich City', 'Fatih Karagümrük S.K.', 'Club Tijuana',
       'Universidad Católica', 'Goiás', 'Benevento', 'Independiente',
       'Qingdao Huanghai F.C.', 'Brentford', 'AEK Athens',
       'Racing Club de Lens', 'Olimpia Asunción', 'Shenzhen FC',
       'Çaykur Rizespor', 'KAA Gent', 'New England Revolution',
       'Cádiz CF', 'FSV Mainz 05', 'Vasco da Gama', 'FC Midtjylland',
       'Al Ain FC', 'Santos Laguna', 'SPAL', 'Perth Glory', 'FC Utrecht',
       'Montreal Impact', 'UD Almería', 'Fortaleza', 'Spezia',
       'FC Basel 1893', 'FC København', 'Godoy Cruz', 'Deportivo Toluca',
       'Nacional de Montevideo', 'Aalborg BK', 'Rio Ave FC', 'FC Metz',
       'Chongqing Dangdai Lifan FC SWM Team', 'Rosenborg BK',
       'FC Red Bull Salzburg', 'Botafogo', 'DSC Arminia Bielefeld',
       'Club Athletico Paranaense', 'RCD Mallorca', 'Pachuca',
       'Swansea City', 'KRC Genk', 'En Avant de Guingamp', 'Lecce',
       'Nîmes Olympique', 'Colo-Colo', 'Stade Malherbe Caen',
       'Columbus Crew SC', 'Junior FC', 'VfB Stuttgart', 'Moreirense FC',
       'Rangers FC', 'Malmö FF', 'Shandong Luneng TaiShan FC',
       'Sparta Praha', 'Hatayspor', 'Chicago Fire',
       'Toulouse Football Club', 'FC Seoul', 'Antalyaspor',
       'Deportivo Cali', 'Kaizer Chiefs', 'Real Zaragoza',
       'Atlético Clube Goianiense', 'Puebla FC', 'Fortuna Düsseldorf',
       'Western United FC', 'Astra Giurgiu', 'Henan Jianye FC', 'Bahia',
       'Famalicão', 'Atiker Konyaspor', 'Peñarol', 'DC United',
       'New York City FC', 'Argentinos Juniors', 'U.N.A.M.',
       'Minnesota United FC', 'Nottingham Forest',
       'Independiente del Valle', 'Defensa y Justicia',
       'Philadelphia Union', "Newell's Old Boys", 'Rosario Central',
       'Atlético de San Luis', 'FC Dallas', 'Denizlispor',
       'Yeni Malatyaspor', 'Club Atlético Colón', 'Houston Dynamo',
       'Millwall', 'Clube Sport Marítimo', 'MKE Ankaragücü',
       'Guadalajara', 'Boavista FC', 'Sporting Kansas City',
       'Atlético Nacional', 'CD Lugo', 'New York Red Bulls', 'PAOK',
       'SC Heerenveen', 'Daegu FC', 'Preston North End', 'Damac FC',
       'Brescia', 'VfL Bochum 1848', 'Vancouver Whitecaps FC',
       'SV Sandhausen', 'Royal Excel Mouscron', 'Dijon FCO', 'Molde FK',
       'Panathinaikos FC', 'LASK Linz', 'Ulsan Hyundai FC',
       'Real Salt Lake', 'FC Luzern', 'Viktoria Plzeň', 'Orlando Pirates',
       'Al Ittihad', 'FC Nürnberg', 'Standard de Liège', 'Rayo Vallecano',
       'Club Libertad', 'Jeonbuk Hyundai Motors',
       'Western Sydney Wanderers', 'Unión de Santa Fe', 'FC Sion',
       'Sydney FC', 'Hannover 96', 'Real Sporting de Gijón',
       'FC Cincinnati', 'ESTAC Troyes', 'San Jose Earthquakes',
       'Club Guaraní', 'FC Lorient', 'Gençlerbirliği SK',
       'Sporting de Charleroi', 'Wisła Kraków', 'Al Taawoun', 'Reading',
       'Gazişehir Gaziantep F.K.', 'Blackburn Rovers', 'Kashiwa Reysol',
       'FK Bodø/Glimt', 'Willem II', 'Vitesse', 'Gil Vicente FC',
       'SønderjyskE', 'Yokohama F. Marinos', 'FC St. Gallen',
       'Club Atlético Aldosivi', 'Göztepe SK', 'Holstein Kiel',
       'FC Juárez', 'FCSB (Steaua)', 'Ettifaq FC', 'KAS Eupen',
       'FC Tokyo', 'Melbourne City FC', 'Universitatea Craiova',
       'CD Tondela', 'Wolfsberger AC', 'Ceará Sporting Club',
       'River Plate Asunción', 'Stoke City', 'Paris FC', 'IFK Norrköping',
       'Crotone', 'Cardiff City', 'América de Cali', 'Al Faisaly',
       'Independiente Medellín', 'Portimonense SC', 'CD Tenerife',
       'Heracles Almelo', 'Nashville SC', 'SK Rapid Wien',
       'Kawasaki Frontale', 'Club Necaxa', 'Chievo Verona', 'Lech Poznań',
       'AIK', 'FK Austria Wien', 'Querétaro', 'FC Heidenheim 1846',
       'Legia Warszawa', 'Club Atlético Banfield', 'Os Belenenses',
       'Huddersfield Town', 'KSV Cercle Brugge', 'LDU Quito',
       'Gimnasia y Esgrima La Plata', 'Gamba Osaka', 'Middlesbrough',
       'Servette FC', 'Empoli', 'Real Oviedo', 'Kasimpaşa SK', 'CFR Cluj',
       'Millonarios FC', 'FC Paços de Ferreira', 'Sint-Truidense VV',
       'AD Alcorcón', 'Colorado Rapids', 'Dinamo Bucureşti',
       'Cerezo Osaka', 'FC Emmen', 'Sheffield Wednesday',
       'FC Erzgebirge Aue', 'Raków Częstochowa', 'Atlético Tucumán',
       'SV Darmstadt 98', 'Bristol City', 'Oud-Heverlee Leuven',
       'Barnsley', 'Queens Park Rangers', 'Sangju Sangmu FC',
       'Helsingborgs IF', 'AC Ajaccio', 'Oceânico FC',
       'Club Atlético Talleres', 'Al Hazem', 'SC Paderborn 07',
       'Club Atlético Huracán', 'KV Kortrijk', 'El Nacional',
       'Mazatlán FC', 'Aberdeen', 'CD Mirandés', 'SV Zulte-Waregem',
       'Piast Gliwice', 'Djurgårdens IF', 'Central Córdoba',
       'Wellington Phoenix', 'Deportivo Binacional', 'Patronato',
       'SpVgg Greuther Fürth', 'IFK Göteborg', 'FC Cartagena',
       'Santa Clara', 'FC Twente', 'Farense', 'ADO Den Haag',
       'AJ Auxerre', 'Al Fateh', 'Valenciennes FC',
       'Hokkaido Consadole Sapporo', 'FC St. Pauli', 'Albacete BP',
       'FC Kaiserslautern', 'Al Fayha', 'Incheon United FC',
       'KV Mechelen', 'Pohang Steelers', 'CD Nacional', 'Unión La Calera',
       'BB Erzurumspor', 'Kashima Antlers', 'Arsenal de Sarandí',
       'HJK Helsinki', 'Karlsruher SC', 'Aarhus GF', 'FC Zürich',
       'Barcelona Sporting Club', 'SG Dynamo Dresden',
       'Sanfrecce Hiroshima', 'Al Raed', 'SD Ponferradina', 'Brøndby IF',
       'Lechia Gdańsk', 'FC Viitorul', 'SK Sturm Graz', 'IF Elfsborg',
       'Gangwon FC', 'Melgar FBC', 'Club Atlético Grau',
       'Jagiellonia Białystok', 'Waasland-Beveren', 'VfL Osnabrück',
       'Nagoya Grampus', 'CF Fuenlabrada', 'Shamrock Rovers',
       'Shimizu S-Pulse', 'RKC Waalwijk', 'Vålerenga Fotball',
       'Clermont Foot 63', 'FC Ingolstadt 04', 'FC Würzburger Kickers',
       'Górnik Zabrze', 'Charlton Athletic', 'Beerschot AC',
       'Coquimbo Unido', 'Viktoria Köln', 'Hull City', 'Málaga CF',
       'FC Nordsjælland', 'UD Las Palmas', 'VVV-Venlo', 'GwangJu FC',
       'Chamois Niortais Football Club', 'FC Lugano', 'Cusco FC',
       'Sparta Rotterdam', 'Sol de América', 'PEC Zwolle',
       'Pogoń Szczecin', 'Doncaster Rovers', 'Kristiansund BK',
       'Liverpool Fútbol Club', 'Club Bolívar', 'Urawa Red Diamonds',
       'SK Brann', 'Eintracht Braunschweig', 'Nacional Asunción',
       'Melbourne Victory', 'Kilmarnock', 'Dundalk',
       'SSV Jahn Regensburg', 'Abha Club', 'Club Atlético Tigre',
       'Suwon Samsung Bluewings', 'Shonan Bellmare', 'SD Aucas', 'Emelec',
       'Fortuna Sittard', 'La Berrichonne de Châteauroux',
       'Śląsk Wrocław', 'Coventry City', 'Sunderland', 'Alianza Lima',
       'Hammarby IF', 'Cracovia', 'CE Sabadell FC', 'Oita Trinita',
       'BK Häcken', 'Luton Town', 'Le Havre AC', 'IK Sirius',
       'Zagłębie Lubin', 'Grenoble Foot 38', 'Macarthur FC',
       'Rodez Aveyron Football', 'Vegalta Sendai', 'Motherwell',
       'SV Wehen Wiesbaden', 'Audax Italiano', 'Gaz Metan Mediaş',
       'Portsmouth', 'Hibernian', 'Always Ready', 'UD Logroñés',
       'FC Voluntari', 'FC Hermannstadt', 'AS Nancy Lorraine',
       'Rotherham United', 'Fleetwood Town', 'Jorge Wilstermann',
       'Odense Boldklub', 'MSV Duisburg', 'FC Sochaux-Montbéliard',
       'Milton Keynes Dons', 'River Plate Montevideo', 'Delfín SC',
       'Universidad Católica del Ecuador', 'Deportivo Pasto',
       'KV Oostende', 'Club Plaza Colonia', 'Wigan Athletic',
       'FC Botoşani', 'C.D. Castellón', 'SCR Altach', 'Örebro SK',
       'TSV Hartberg', 'Stabæk Fotball', 'Wycombe Wanderers',
       'St. Johnstone FC', 'Oxford United', 'Lincoln City', 'Randers FC',
       'Viking FK', 'FC Chambly Oise', 'Dundee United',
       'Oriente Petrolero', 'Odds BK', 'Nacional Potosí', 'Sepsi OSK',
       'FC Hansa Rostock', 'Lyngby BK', 'SpVgg Unterhaching',
       'Brisbane Roar', 'Seongnam FC', 'SV Ried', 'CD Huachipato',
       'WSG Tirol', 'Podbeskidzie Bielsko-Biała', 'Peterborough United',
       'Club Blooming', 'Wisła Płock', 'Busan IPark', 'FSV Zwickau',
       'Mjøndalen IF', 'Vejle Boldklub', 'Pau FC', 'FC Lausanne-Sport',
       'Estudiantes de Mérida', 'Sagan Tosu', 'SV Waldhof Mannheim',
       'Sport Huancayo', 'Hallescher FC', 'Kalmar FF', 'St. Mirren',
       'SKN St. Pölten', 'Sarpsborg 08 FF', 'Shrewsbury',
       'TSV 1860 München', 'SV Meppen', 'Ipswich Town', 'IK Start',
       'Adelaide United', 'Stal Mielec', 'Centro Atlético Fénix',
       'Newcastle Jets', 'Livingston FC', 'AC Mineros de Guayana',
       'AFC Wimbledon', 'Burton Albion', 'Al Adalah', 'Warta Poznań',
       'USL Dunkerque', 'Bristol Rovers', 'UTA Arad', 'Östersunds FK',
       'Sportivo Luqueño', 'Politehnica Iaşi', 'Salford City',
       'Central Coast Mariners', 'Caracas FC', 'AC Horsens',
       'Plymouth Argyle', 'Aalesunds FK', 'Crewe Alexandra',
       'Chindia Târgovişte', 'Oldham Athletic', 'Yokohama FC',
       'Blackpool', 'Northampton Town', 'Bayern München II',
       'FK Haugesund', 'KFC Uerdingen 05', 'Forest Green Rovers',
       'Cheltenham Town', 'Strømsgodset IF', 'Mjällby AIF', 'Exeter City',
       'Cambridge United', 'Grimsby Town', 'FC Vaduz', 'Türkgücü München',
       'VfB Lübeck', 'Bolton Wanderers', 'Bradford City', 'FC Magdeburg',
       'FC Admira Wacker Mödling', 'Hamilton Academical FC', 'Aragua FC',
       'Accrington Stanley', 'Swindon Town', 'Carlisle United',
       'FC Argeș', 'Port Vale', 'Academica Clinceni', 'Rochdale',
       'Gillingham', 'Tranmere Rovers', 'Southend United',
       'FC Saarbrücken', 'Colchester United', 'Mansfield Town',
       'Falkenbergs FF', 'SC Verl', 'Varbergs BoIS', 'Crawley Town',
       'Sandefjord Fotball', 'Newport County', 'Bohemian FC',
       'Ross County FC', 'Scunthorpe United', 'Morecambe', 'Walsall',
       'Leyton Orient', 'Stevenage', 'Barrow', 'Derry City',
       'Llaneros de Guanare', 'Sligo Rovers', 'Zamora FC',
       "St. Patrick's Athletic", 'Cork City', 'Shelbourne FC',
       'Harrogate Town', 'Waterford FC', 'Finn Harps'], dtype=object)

### data['Height']

In [89]:
###Change data['Height'] to int by removing the 'cm' 
data['Height'] = data['Height'].str.replace('cm','')
data['Height'].unique()

array(['170', '187', '188', '181', '175', '184', '191', '178', '193',
       '185', '199', '173', '168', '176', '177', '183', '180', '189',
       '179', '195', '172', '182', '186', '192', '165', '194', '167',
       '196', '163', '190', '174', '169', '171', '197', '200', '166',
       '6\'2"', '164', '198', '6\'3"', '6\'5"', '5\'11"', '6\'4"',
       '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"', '5\'4"',
       '201', '158', '162', '161', '160', '203', '157', '156', '202',
       '159', '206', '155'], dtype=object)

There are some values that are not in cm, we should change to cm so the data are uniform in cm

In [90]:
data['Height'] = data['Height'].str.replace('5\'4"','163')
data['Height'] = data['Height'].str.replace('5\'6"','168')
data['Height'] = data['Height'].str.replace('5\'7"','170')
data['Height'] = data['Height'].str.replace('5\'9"','175')
data['Height'] = data['Height'].str.replace('5\'10"','178')
data['Height'] = data['Height'].str.replace('5\'11"','180')
data['Height'] = data['Height'].str.replace('6\'0"','183')
data['Height'] = data['Height'].str.replace('6\'1"','185')
data['Height'] = data['Height'].str.replace('6\'2"','188')
data['Height'] = data['Height'].str.replace('6\'3"','191')
data['Height'] = data['Height'].str.replace('6\'4"','193')
data['Height'] = data['Height'].str.replace('6\'5"','196')

In [91]:
data['Height'].unique()

array(['170', '187', '188', '181', '175', '184', '191', '178', '193',
       '185', '199', '173', '168', '176', '177', '183', '180', '189',
       '179', '195', '172', '182', '186', '192', '165', '194', '167',
       '196', '163', '190', '174', '169', '171', '197', '200', '166',
       '164', '198', '201', '158', '162', '161', '160', '203', '157',
       '156', '202', '159', '206', '155'], dtype=object)

data['Height'] are now uniform in format

### data['Weight]

In [92]:
###Change data['Weight'] to int by removing the 'kg' 
data['Weight'] = data['Weight'].str.replace('kg','')
data['Weight'].unique()

array(['72', '83', '87', '70', '68', '80', '71', '91', '73', '85', '92',
       '69', '84', '96', '81', '82', '75', '86', '89', '74', '76', '64',
       '78', '90', '66', '60', '94', '79', '67', '65', '59', '61', '93',
       '88', '97', '77', '62', '63', '95', '100', '58', '183lbs',
       '179lbs', '172lbs', '196lbs', '176lbs', '185lbs', '170lbs',
       '203lbs', '168lbs', '161lbs', '146lbs', '130lbs', '190lbs',
       '174lbs', '148lbs', '165lbs', '159lbs', '192lbs', '181lbs',
       '139lbs', '154lbs', '157lbs', '163lbs', '98', '103', '99', '102',
       '56', '101', '57', '55', '104', '107', '110', '53', '50', '54',
       '52'], dtype=object)

There are some values that are not in kg, we should change to kg so the data are uniform in kg

In [93]:
data['Weight'] = data['Weight'].str.replace('146lbs','66')
data['Weight'] = data['Weight'].str.replace('148lbs','67')
data['Weight'] = data['Weight'].str.replace('130lbs','59')
data['Weight'] = data['Weight'].str.replace('179lbs','81')
data['Weight'] = data['Weight'].str.replace('172lbs','78')
data['Weight'] = data['Weight'].str.replace('196lbs','89')
data['Weight'] = data['Weight'].str.replace('176lbs','80')
data['Weight'] = data['Weight'].str.replace('185lbs','84')
data['Weight'] = data['Weight'].str.replace('170lbs','77')
data['Weight'] = data['Weight'].str.replace('203lbs','92')
data['Weight'] = data['Weight'].str.replace('168lbs','76')
data['Weight'] = data['Weight'].str.replace('161lbs','73')
data['Weight'] = data['Weight'].str.replace('190lbs','86')
data['Weight'] = data['Weight'].str.replace('174lbs','79')
data['Weight'] = data['Weight'].str.replace('165lbs','75')
data['Weight'] = data['Weight'].str.replace('159lbs','72')
data['Weight'] = data['Weight'].str.replace('192lbs','87')
data['Weight'] = data['Weight'].str.replace('181lbs','82')
data['Weight'] = data['Weight'].str.replace('139lbs','63')
data['Weight'] = data['Weight'].str.replace('154lbs','70')
data['Weight'] = data['Weight'].str.replace('157lbs','71')
data['Weight'] = data['Weight'].str.replace('163lbs','74')
data['Weight'] = data['Weight'].str.replace('183lbs','83')

In [94]:
data['Weight'].unique()

array(['72', '83', '87', '70', '68', '80', '71', '91', '73', '85', '92',
       '69', '84', '96', '81', '82', '75', '86', '89', '74', '76', '64',
       '78', '90', '66', '60', '94', '79', '67', '65', '59', '61', '93',
       '88', '97', '77', '62', '63', '95', '100', '58', '98', '103', '99',
       '102', '56', '101', '57', '55', '104', '107', '110', '53', '50',
       '54', '52'], dtype=object)

data['Weight'] are now uniform in format

### data['Joined']

In [95]:
data['Joined'].unique()

array(['Jul 1, 2004', 'Jul 10, 2018', 'Jul 16, 2014', ..., 'Sep 22, 2018',
       'Feb 28, 2015', 'Mar 6, 2018'], dtype=object)

In [96]:
#convert to datetime format
data['Joined'] = pd.to_datetime(data['Joined'], format = '%b %d, %Y')

#convert to yyyy/mm/dd format
data['Joined'] = data['Joined'].dt.strftime('%Y/%m/%d')

In [97]:
data['Joined'].unique()

array(['2004/07/01', '2018/07/10', '2014/07/16', ..., '2018/09/22',
       '2015/02/28', '2018/03/06'], dtype=object)

### data['Value'], data['Wage'], and data['Release Clause']

In [98]:
#Removing the currency symbol and convert M to millon and K to thousands in numbers
def convert_currency(amount):
    amount = amount.replace('€','') #removing currency symbol
    if 'M' in amount:
        amount = float(amount.replace('M','')) * 1000000 # convert to million
    elif 'K' in amount:
        amount = float(amount.replace('K','')) * 1000 #convert to thousands
    else:
        amount = float(amount)
    return amount

data['Value'] = data['Value'].apply(convert_currency)
data['Wage'] = data['Wage'].apply(convert_currency)
data['Release Clause'] = data['Release Clause'].apply(convert_currency)

In [99]:
data[['Value','Wage','Release Clause']]

             Value      Wage  Release Clause
0      103500000.0  560000.0     138400000.0
1       63000000.0  220000.0      75900000.0
2      120000000.0  125000.0     159400000.0
3      129000000.0  370000.0     161000000.0
4      132000000.0  270000.0     166500000.0
...            ...       ...             ...
18974     100000.0    1000.0         70000.0
18975     130000.0     500.0        165000.0
18976     120000.0     500.0        131000.0
18977     100000.0    2000.0         88000.0
18978     100000.0    1000.0         79000.0

[18979 rows x 3 columns]

### data['WF'], data['SM'], and data['IR']

In [100]:
#removing the star symbol in w/f,sm.ir
data['W/F'] = data['W/F'].str.replace('★','')
data['SM'] = data['SM'].str.replace('★','')
data['IR'] = data['IR'].str.replace('★','')

In [101]:
data[['W/F','SM','IR']]

      W/F SM  IR
0      4   4  5
1      4   5  5
2      3   1  3
3      5   4  4
4      5   5  5
...    .. ..  ..
18974  2   2  1
18975  2   2  1
18976  2   2  1
18977  3   2  1
18978  3   2  1

[18979 rows x 3 columns]

### data['Loan Date End'] and data['Contract']

Loan Date End is the date when the player's loan contract ends. Some values are null (NaN) since the contract has expired as we see in Contract column, but some remain on loan and free.

In [102]:
data['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [103]:
data[data['Contract']=='Free'][['Contract','Loan Date End']]

      Contract Loan Date End
289       Free           NaN
292       Free           NaN
369       Free           NaN
374       Free           NaN
375       Free           NaN
...        ...           ...
17220     Free           NaN
17343     Free           NaN
17659     Free           NaN
17661     Free           NaN
18205     Free           NaN

[237 rows x 2 columns]

In [104]:
data[['month','Contract Expiry Year']] = data['Loan Date End'].str.split(',', expand = True).apply(lambda x: x.str.strip())
data.drop(['month','Loan Date End'] , axis =1, inplace = True)
data.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract Expiry Year
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,Low,5,85,92,91,95,38,65,771,NaN
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,Low,5,89,93,81,89,35,77,562,NaN
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,Medium,3,87,92,78,90,52,90,150,NaN
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,High,4,76,86,93,88,64,78,207,NaN
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,Medium,5,91,85,86,94,36,59,595,NaN

In [105]:
data['Contract Expiry Year'].unique()

array([nan, '2021', '2020', '2022', '2023'], dtype=object)

Fill the NaN values with year by extract 4 characters (year) from Contract column

In [106]:
end_year= data['Contract'].apply(lambda x : x[-4:])

data['Contract Expiry Year'] = data['Contract Expiry Year'].fillna(end_year)
data['Contract Expiry Year'].replace('Free','0',inplace=True)
data['Contract Expiry Year'].unique()

array(['2021', '2022', '2023', '2024', '2025', '2026', '0', '2028',
       '2020', '2027'], dtype=object)

In [107]:
data['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', nan, 11.0,
       2.0, 1.0, 31.0, 3.0, 10.0, 9.0, 17.0, 7.0, 4.0, 6.0], dtype=object)

In [108]:
data['Hits'] = data['Hits'].fillna(0)
data['Hits'] = data['Hits'].replace({'k':'000','K':'000'}, regex = True).astype(float)
#Updated data
data[['Hits']]

        Hits
0      771.0
1      562.0
2      150.0
3      207.0
4      595.0
...      ...
18974    0.0
18975    0.0
18976    0.0
18977    0.0
18978    0.0

[18979 rows x 1 columns]

In [109]:
data

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract Expiry Year
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,Low,5,85,92,91,95,38,65,771.0,2021
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,Low,5,89,93,81,89,35,77,562.0,2022
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,Medium,3,87,92,78,90,52,90,150.0,2023
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,High,4,76,86,93,88,64,78,207.0,2023
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,Medium,5,91,85,86,94,36,59,595.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,Wuhan Zall,...,Medium,1,64,28,26,38,48,51,0.0,2022
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,Oldham Athletic,...,Medium,1,64,40,48,49,35,45,0.0,2021
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,Derry City,...,Medium,1,63,39,44,46,40,53,0.0,2020
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,Dalian YiFang FC,...,Medium,1,58,49,41,49,30,44,0.0,2022
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,Dalian YiFang FC,...,Medium,1,62,22,39,42,45,55,0.0,2023

## Dealing with datatype

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    18979 non-null  int64
 1   Name                  18979 non-null  object
 2   LongName              18979 non-null  object
 3   photoUrl              18979 non-null  object
 4   playerUrl             18979 non-null  object
 5   Nationality           18979 non-null  object
 6   Age                   18979 non-null  int64
 7   ↓OVA                  18979 non-null  int64
 8   POT                   18979 non-null  int64
 9   Club                  18979 non-null  object
 10  Contract              18979 non-null  object
 11  Positions             18979 non-null  object
 12  Height                18979 non-null  object
 13  Weight                18979 non-null  object
 14  Preferred Foot        18979 non-null  object
 15  BOV                   18979 non-null  int64
 16  Best Position         18979 non-null  object
 17  Joined                18979 non-null  object
 18  Value                 18979 non-null  float64
 19  Wage                  18979 non-null  float64
 20  Release Clause        18979 non-null  float64
 21  Attacking             18979 non-null  int64
 22  Crossing              18979 non-null  int64
 23  Finishing             18979 non-null  int64
 24  Heading Accuracy      18979 non-null  int64
 25  Short Passing         18979 non-null  int64
 26  Volleys               18979 non-null  int64
 27  Skill                 18979 non-null  int64
 28  Dribbling             18979 non-null  int64
 29  Curve                 18979 non-null  int64
 30  FK Accuracy           18979 non-null  int64
 31  Long Passing          18979 non-null  int64
 32  Ball Control          18979 non-null  int64
 33  Movement              18979 non-null  int64
 34  Acceleration          18979 non-null  int64
 35  Sprint Speed          18979 non-null  int64
 36  Agility               18979 non-null  int64
 37  Reactions             18979 non-null  int64
 38  Balance               18979 non-null  int64
 39  Power                 18979 non-null  int64
 40  Shot Power            18979 non-null  int64
 41  Jumping               18979 non-null  int64
 42  Stamina               18979 non-null  int64
 43  Strength              18979 non-null  int64
 44  Long Shots            18979 non-null  int64
 45  Mentality             18979 non-null  int64
 46  Aggression            18979 non-null  int64
 47  Interceptions         18979 non-null  int64
 48  Positioning           18979 non-null  int64
 49  Vision                18979 non-null  int64
 50  Penalties             18979 non-null  int64
 51  Composure             18979 non-null  int64
 52  Defending             18979 non-null  int64
 53  Marking               18979 non-null  int64
 54  Standing Tackle       18979 non-null  int64
 55  Sliding Tackle        18979 non-null  int64
 56  Goalkeeping           18979 non-null  int64
 57  GK Diving             18979 non-null  int64
 58  GK Handling           18979 non-null  int64
 59  GK Kicking            18979 non-null  int64
 60  GK Positioning        18979 non-null  int64
 61  GK Reflexes           18979 non-null  int64
 62  Total Stats           18979 non-null  int64
 63  Base Stats            18979 non-null  int64
 64  W/F                   18979 non-null  object
 65  SM                    18979 non-null  object
 66  A/W                   18979 non-null  object
 67  D/W                   18979 non-null  object
 68  IR                    18979 non-null  object
 69  PAC                   18979 non-null  int64
 70  SHO                   18979 non-null  int64
 71  PAS                   18979 non-null  int64
 72  DRI                   18979 non-null  int64
 73  DEF                   18979 non-null  int64
 74  PHY                   18979 non-null  int64
 75  Hits                  18979 non-null  float64
 76  Contract Expiry Year  18979 non-null  object
dtypes: float64(4), int64(54), object(19)
memory usage: 11.1+ MB

In [111]:
data['Height'] = data['Height'].astype(int)
data['Weight'] = data['Weight'].astype(int)
data['W/F'] = data['W/F'].astype(int)
data['SM'] = data['SM'].astype(int)
data['IR'] = data['IR'].astype(int)
data['Value'] = data['Value'].astype(int)
data['Wage'] = data['Wage'].astype(int)
data['Release Clause'] = data['Release Clause'].astype(int)
data['Hits'] = data['Hits'].astype(int)
data['Contract Expiry Year'] = data['Contract Expiry Year'].astype(int)

In [112]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    18979 non-null  int64
 1   Name                  18979 non-null  object
 2   LongName              18979 non-null  object
 3   photoUrl              18979 non-null  object
 4   playerUrl             18979 non-null  object
 5   Nationality           18979 non-null  object
 6   Age                   18979 non-null  int64
 7   ↓OVA                  18979 non-null  int64
 8   POT                   18979 non-null  int64
 9   Club                  18979 non-null  object
 10  Contract              18979 non-null  object
 11  Positions             18979 non-null  object
 12  Height                18979 non-null  int64
 13  Weight                18979 non-null  int64
 14  Preferred Foot        18979 non-null  object
 15  BOV                   18979 non-null  int64
 16  Best Position         18979 non-null  object
 17  Joined                18979 non-null  object
 18  Value                 18979 non-null  int64
 19  Wage                  18979 non-null  int64
 20  Release Clause        18979 non-null  int64
 21  Attacking             18979 non-null  int64
 22  Crossing              18979 non-null  int64
 23  Finishing             18979 non-null  int64
 24  Heading Accuracy      18979 non-null  int64
 25  Short Passing         18979 non-null  int64
 26  Volleys               18979 non-null  int64
 27  Skill                 18979 non-null  int64
 28  Dribbling             18979 non-null  int64
 29  Curve                 18979 non-null  int64
 30  FK Accuracy           18979 non-null  int64
 31  Long Passing          18979 non-null  int64
 32  Ball Control          18979 non-null  int64
 33  Movement              18979 non-null  int64
 34  Acceleration          18979 non-null  int64
 35  Sprint Speed          18979 non-null  int64
 36  Agility               18979 non-null  int64
 37  Reactions             18979 non-null  int64
 38  Balance               18979 non-null  int64
 39  Power                 18979 non-null  int64
 40  Shot Power            18979 non-null  int64
 41  Jumping               18979 non-null  int64
 42  Stamina               18979 non-null  int64
 43  Strength              18979 non-null  int64
 44  Long Shots            18979 non-null  int64
 45  Mentality             18979 non-null  int64
 46  Aggression            18979 non-null  int64
 47  Interceptions         18979 non-null  int64
 48  Positioning           18979 non-null  int64
 49  Vision                18979 non-null  int64
 50  Penalties             18979 non-null  int64
 51  Composure             18979 non-null  int64
 52  Defending             18979 non-null  int64
 53  Marking               18979 non-null  int64
 54  Standing Tackle       18979 non-null  int64
 55  Sliding Tackle        18979 non-null  int64
 56  Goalkeeping           18979 non-null  int64
 57  GK Diving             18979 non-null  int64
 58  GK Handling           18979 non-null  int64
 59  GK Kicking            18979 non-null  int64
 60  GK Positioning        18979 non-null  int64
 61  GK Reflexes           18979 non-null  int64
 62  Total Stats           18979 non-null  int64
 63  Base Stats            18979 non-null  int64
 64  W/F                   18979 non-null  int64
 65  SM                    18979 non-null  int64
 66  A/W                   18979 non-null  object
 67  D/W                   18979 non-null  object
 68  IR                    18979 non-null  int64
 69  PAC                   18979 non-null  int64
 70  SHO                   18979 non-null  int64
 71  PAS                   18979 non-null  int64
 72  DRI                   18979 non-null  int64
 73  DEF                   18979 non-null  int64
 74  PHY                   18979 non-null  int64
 75  Hits                  18979 non-null  int64
 76  Contract Expiry Year  18979 non-null  int64
dtypes: int64(64), object(13)
memory usage: 11.1+ MB

## Dealing with duplicate data

In [113]:
print(data.duplicated().sum())

0

There are no duplicates in this dataframe

## Column selection

After we cleaned up the dataframe, we should select what columns to use for our analysis. We can drop columns that are not used.

In [114]:
#Drop Name, photoUrl, playerUrl, and contract columns
data.drop(['Contract','Name','photoUrl','playerUrl'], axis = 1, inplace = True)
data

,ID,LongName,Nationality,Age,↓OVA,POT,Club,Positions,Height,Weight,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract Expiry Year
0,158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",170,72,...,Low,5,85,92,91,95,38,65,771,2021
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,"ST, LW",187,83,...,Low,5,89,93,81,89,35,77,562,2022
2,200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,GK,188,87,...,Medium,3,87,92,78,90,52,90,150,2023
3,192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,"CAM, CM",181,70,...,High,4,76,86,93,88,64,78,207,2023
4,190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",175,68,...,Medium,5,91,85,86,94,36,59,595,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Ao Xia,China PR,21,47,55,Wuhan Zall,CB,178,66,...,Medium,1,64,28,26,38,48,51,0,2022
18975,258760,Ben Hough,England,17,47,67,Oldham Athletic,CM,175,65,...,Medium,1,64,40,48,49,35,45,0,2021
18976,252757,Ronan McKinley,England,18,47,65,Derry City,CM,179,74,...,Medium,1,63,39,44,46,40,53,0,2020
18977,243790,Zhen'ao Wang,China PR,20,47,57,Dalian YiFang FC,RW,175,69,...,Medium,1,58,49,41,49,30,44,0,2022
18978,252520,Xiao Zhou,China PR,21,47,57,Dalian YiFang FC,"CB, LB",188,75,...,Medium,1,62,22,39,42,45,55,0,2023

# Save the data

In [115]:
data.to_csv('data_challange.csv',index=False)